### ISSUE TITLE
Adding primefaces premium jar themes

### ISSUE THREAD

**Issue by FrancescoTran** [joinfaces/joinfaces#1015]
I am trying to add a primefaces premium theme without success.
If I set joinfaces.primefaces.theme=omega in the application properties everything works.
When I try to add the .jar file with another theme and change that parameter I get an error, probably I am using the wrong location.

**Comment by melloware** [comment]
I do this with the Babylon Premium Theme layout.

1. Add your JAR to pom.xml.
```xml
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>babylon-theme</artifactId>
            <version>X.X.X</version>
        </dependency>
```

2. Add the resources for premium theme in `\src\main\resources\META-INF\resources\babylon-layout` or whatever your layout is called.

3. In your Template XHTML where you are including JS and CSS make sure to add your layout CSS and JS like...

```xml
        <h:outputStylesheet name="css/nanoscroller.css" library="babylon-layout" />
        <h:outputStylesheet name="css/primeflex.css" library="babylon-layout" />
        <h:outputStylesheet name="css/layout-bluegrey.css" library="babylon-layout" />
        <h:outputScript name="js/nanoscroller.js" library="babylon-layout" target="head"/>
        <h:outputScript name="js/layout.js" library="babylon-layout" target="head"/>
```

**Comment by FrancescoTran** [comment]
I was able to run it, thanks
