### ISSUE TITLE
This question is not a bug, but a question

### ISSUE THREAD

**Issue by eric-5512** [joinfaces/joinfaces#1137]
Excuse me, are there any successful online examples now, because I have been worried about performance issues.

**Comment by melloware** [comment]
Not sure what you are looking for?  I have used JoinFaces in PRD apps and it works great. Performance issues are usually if your Database Model is bad or your are making really inefficient queries but that has nothing to do with JoinFaces.

**Comment by eric-5512** [comment]
HI @melloware 

Sorry, I am not saying that JoinFaces is slow.

I mean combined with spring boot and jsf, how is the load capacity in terms of memory consumption and user usage?

**Comment by melloware** [comment]
It performs well if you are diligent about your use of Session and ViewScoped beans.   Like anything an app can be written poorly and perform poorly.

**Comment by eric-5512** [comment]
HI @melloware 

Thank you for your answer.
