### ISSUE TITLE
Regarding the display of abnormal login information

### ISSUE THREAD

**Issue by eric-5512** [joinfaces/joinfaces#1138]
HI 

I have a question, but this is not a bug.

1:When I fail to log in and verify, I will walk into the method based on the AuthenticationFailureHandler interface.

2:I want to put the error message into facesContext.addMessage and display it through p:messages

3:Obviously, it is impossible to do this now, and it should not be in a context. Do we have any better way now?

**Comment by stefan-dan** [comment]
If the login fails you could redirect to the same login page with a HTTP parameter in the URL using 
`.failureUrl("/login.jsf?error=true")`  in the **WebSecurityConfiguration** file.

This will allow you to display the error message using the condition `rendered="${!empty param['error']}"`

For more information read this article: https://codenotfound.com/jsf-primefaces-spring-security-example.html

**Comment by eric-5512** [comment]
@stefan-dan 

OK THANK YOU
