### ISSUE TITLE
Add MyFaces Trinidad autoconfiguration

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#132]
See https://github.com/joinfaces/joinfaces/wiki/Creating-Spring-Boot-Starter-to-specific-JSF-component-library

**Comment by persapiens** [comment]
Trinidad is in [maintenance mode.](https://lists.apache.org/thread.html/0d01a367ac9fa9b11476d86be964b126cdb1b9d564082bd4c198eca4@%3Cdev.myfaces.apache.org%3E)

**Comment by larsgrefer** [comment]
MyFaces Trinidad seems to be dead.
