### ISSUE TITLE
 joinfaces / joinfaces-maven-jar-example Public - jar does not run with jdk16, jdk17

### ISSUE THREAD

**Issue by riewek** [joinfaces/joinfaces#1326]
Reproduce:
Checkout
https://github.com/joinfaces/joinfaces-maven-jar-example/tree/e1e3aa5585247a82ba671a0317f83554028795a4

Maven Install

Run with jdk16
...\bellsoft-jdk16+36-windows-amd64\jdk-16\bin\java -jar joinfaces-example-4.6.0.jar

Stacktrace:
[stacktrace.txt](https://github.com/joinfaces/joinfaces/files/7583358/stacktrace.txt)

Are there any jdk options to make it run in a jar file?

Thanks for the joinfaces project :)

**Comment by larsgrefer** [comment]
Could you try running it with `--add-opens java.base/java.lang=ALL-UNNAMED` please?

**Comment by riewek** [comment]
It Works!
\bellsoft-jdk16+36-windows-amd64\jdk-16\bin\java --add-opens java.base/java.lang=ALL-UNNAMED -jar joinfaces-example-4.6.0.jar
\bellsoft-jdk17.0.1+12-windows-amd64-full\jdk-17.0.1-full\bin\java --add-opens java.base/java.lang=ALL-UNNAMED -jar joinfaces-example-4.6.0.jar

**Comment by nikita-rogovyi** [comment]
> Could you try running it with `--add-opens java.base/java.lang=ALL-UNNAMED` please?

should it be fixed in future releases or will be as is?

**Comment by orange-buffalo** [comment]
`--add-opens` is considered a workaround to support legacy code that accesses JDK internals. I believe the code must be adjusted to not use those internals (or cause JVM believe it uses them, like proxying `java.lang.Object` with CGLIB).

**Comment by larsgrefer** [comment]
This should now be fixed for 4.6.3+, 4.7.x+ and 5.0.0

If you still have this problem with the latest JoinFaces versions, please open a new issue.

**Comment by nikita-rogovyi** [comment]
the same issue is still present with 
- joinfaces 4.6.3
- jre 17

`--add-opens java.base/java.lang=ALL-UNNAMED` still helps

**Comment by larsgrefer** [comment]
@nikita-rogovyi Please open a new issue with an example project which reproduces your problem
