### ISSUE TITLE
invalid primefaces starter pom in 5.0.x

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#1360]
According to discussion #1352, I see that [primefaces-spring-boot-starter pom](https://oss.sonatype.org/service/local/repositories/snapshots/content/org/joinfaces/primefaces-spring-boot-starter/5.0.x-SNAPSHOT/primefaces-spring-boot-starter-5.0.x-20220102.014021-19.pom) is invalid. The dependencyManagement section of the libraries org.primefaces:primefaces and org.primefaces.primefaces-extensions:primefaces-extensions does not include jakarta classifier.

I see the following errors when I build [joinfaces example 5.0.x branch](https://github.com/joinfaces/joinfaces-maven-jar-example/tree/joinfaces-5.0.x) with

`./mvnw dependency:tree -X`

`[WARNING] The POM for org.joinfaces:primefaces-spring-boot-starter:jar:5.0.x-20220102.014021-19 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for org.joinfaces:primefaces-spring-boot-starter:5.0.x-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.primefaces:primefaces:jar:jakarta is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.primefaces.extensions:primefaces-extensions:jar:jakarta is missing. @`

So primefaces dependencies are not pulled and joinfaces-example [build fails](https://github.com/joinfaces/joinfaces-maven-jar-example/runs/4715350361?check_suite_focus=true).

**Comment by larsgrefer** [comment]
@persapiens Could you test this again with 5.0.0-m1 ?

**Comment by persapiens** [comment]
[joinfaces example 5.0.x branch](https://github.com/joinfaces/joinfaces-maven-jar-example/tree/joinfaces-5.0.x) it working now. Thanks again.
