### ISSUE TITLE
  @PreDestroy  no trigger

### ISSUE THREAD

**Issue by eric-5512** [joinfaces/joinfaces#1384]
<joinfaces.version>4.6.3</joinfaces.version>

```
<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>primefaces-spring-boot-starter</artifactId>
			<version>${joinfaces.version}</version>
			<exclusions>
                <exclusion>
                    <groupId>org.joinfaces</groupId>
                    <artifactId>tomcat-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
		</dependency>

		<dependency>
		   <groupId>org.joinfaces</groupId>
		   <artifactId>undertow-spring-boot-starter</artifactId>
		   <version>${joinfaces.version}</version>
		</dependency>
```

![image](https://user-images.githubusercontent.com/56282991/151203719-75c39697-77f0-4fc7-af0c-6309cd5e6822.png)

I found out that the ViewScope's @PreDestroy is not triggered anyway

config:

![image](https://user-images.githubusercontent.com/56282991/151204125-9a511a41-4408-43e0-a2f6-ec506012835c.png)

**Comment by larsgrefer** [comment]
The PreDestory should be called when the view is invalidated or when the session expires

**Comment by eric-5512** [comment]
HI @larsgrefer 

I can't know when @ViewScope is destroyed, but I'm prone to memory overflow after a long time.

**Comment by eric-5512** [comment]
@larsgrefer 

why close this issue?

**Comment by larsgrefer** [comment]
Why do you think that view scoped beans cause a memory overflow?
