### ISSUE TITLE
Add Spring support for jakarta CDI beans

### ISSUE THREAD

**Issue by stefan-dan** [joinfaces/joinfaces#1494]
Currently only **javax.*** CDI beans are supported.
### Working example:
```
import javax.inject.Named;

@Named
public JavaxBean {

@Autowired
private SpringBean springbean; // is available

}
```
### Not working example:
```
import jakarta.inject.Named;

@Named
public JakartaBean {

@Autowired
private SpringBean springbean; // is not available

}
```

**Comment by larsgrefer** [comment]
The support for `@Named` is provided by the _Spring Framework_ itself: https://docs.spring.io/spring-framework/docs/5.3.x/reference/html/core.html#beans-named

_Spring Framework_ will switch from `javax.*` to `jakarta.*` with version 6 which will be included in JoinFaces 5

**Comment by stefan-dan** [comment]
Cool, thank you very much.
