### ISSUE TITLE
Request to offer a version including Primefaces12

### ISSUE THREAD

**Issue by StefanSchubert** [joinfaces/joinfaces#1588]
Hi there,

this is not a joinfaces bug, I'm using 5.0.0.M5

<img width="346" alt="image" src="https://user-images.githubusercontent.com/10548043/197861553-6acb598a-5208-4971-a5b6-57fc2dd3a817.png">

for my project I have an issue with the ChartJS version, which is an ingredient of PF11.
See https://github.com/primefaces/primefaces/issues/9339

I looks like that my problem might be solved with a newer version of ChartJS in PF12.
Is there anyway that you could offer a version that includes PF12?

Thanks for maintaining joinfaces :-)

Stefan

**Comment by larsgrefer** [comment]
The next 5.0.x version will ship with PF12 as default.

In the meantime you can just directly depend on `jsf-spring-boot-starter` and your desired PF version

**Comment by StefanSchubert** [comment]
Thanks for the answer. After understanding how chartJS is dealing with the XAxis rendering, I have found a workaround by just emmiting the same month labels 3 times (1st to 3rd of month) on a 3 month scale and 8 times on a year scale.

I haven't tried out to pin  the required PF version as suggested, as I already hat the workaround in place.
But good to know, I might do this when I encounter the next version problem.

**Comment by commonslibs** [comment]
Hi.

I am using Joinfaces 4.7.17 and I notice that the version of FP that is included is also 11.0.6.

Given that, as of today, version 12 is released (and 13) of Primefaces. Could you generate a version of joinfaces that includes, at least, version 12 (currently the latest extension is 12.0.6)?. I think it would be interesting to release a version of Joinfaces with PF 12 and also start releasing versions of JF with version 13 of PF, for 4.7.X joinfaces releases.

On the other hand, two answers above mention that we can indicate a different version of PF than the one that Joinfaces incorporates through "jsf-spring-boot-starter". How could we do it? Could you give an example?

Thank you very much for the effort to maintain Joinfaces!!

**Comment by larsgrefer** [comment]
@commonslibs We won't do any major dependency updates for 4.7.x (and also not for 5.0.x or 5.1.x for that matter)

JoinFaces 4.7.x and 5.0.x will get their last patch at the end of November because the OSS support for Spring Boot 2.7 and 5.0 ends there as well.

If you want to use Primefaces 12 or 13 on JoinFaces 4.7.x, just add an explicit dependency on your desired version:

```
dependencies {
    implementation "org.joinfaces:jsf-spring-boot-starter"
    implementation "org.primefaces:primefaces:12.0.0"
}
```

**Comment by commonslibs** [comment]
> @commonslibs We won't do any major dependency updates for 4.7.x (and also not for 5.0.x or 5.1.x for that matter)
> 
> JoinFaces 4.7.x and 5.0.x will get their last patch at the end of November because the OSS support for Spring Boot 2.7 and 5.0 ends there as well.
> 
> If you want to use Primefaces 12 or 13 on JoinFaces 4.7.x, just add an explicit dependency on your desired version:
> 
> ```
> dependencies {
>     implementation "org.joinfaces:jsf-spring-boot-starter"
>     implementation "org.primefaces:primefaces:12.0.0"
> }
> ```

In a maven project with Joinfaces 4.7.17, I have applied the following changes:

from:
```
<dependency>
   <groupId>org.joinfaces</groupId>
   <artifactId>primefaces-spring-boot-starter</artifactId>
</dependency>
```

to:
```
<dependency>
   <groupId>org.joinfaces</groupId>
   <artifactId>primefaces-spring-boot-starter</artifactId>
   <exclusions>
   <!-- Version 11.0.6 of Primefaces is removed to go up to 13.0.2, the last one available as of 10/30/2023 -->
   <exclusion>
      <groupId>org.primefaces</groupId>
      <artifactId>primefaces</artifactId>
   </exclusion>
   <exclusion>
      <groupId>org.primefaces.extensions</groupId>
      <artifactId>primefaces-extensions</artifactId>
   </exclusion>
   <exclusion>
      <groupId>org.primefaces.extensions</groupId>
      <artifactId>resources-ckeditor</artifactId>
   </exclusion>
   </exclusions>
</dependency>
<!-- Primefaces version 13.0.2 included -->
<dependency>
   <groupId>org.primefaces</groupId>
   <artifactId>primefaces</artifactId>
   <version>13.0.2</version>
</dependency>
<dependency>
   <groupId>org.primefaces.extensions</groupId>
   <artifactId>primefaces-extensions</artifactId>
   <version>13.0.2</version>
</dependency>
```

And the project is now with Primefaces 13.0.2 and it seems to work correctly.

Thank you so much.

**Comment by larsgrefer** [comment]
You could just use this:

```
<dependency>
   <groupId>org.joinfaces</groupId>
   <artifactId>jsf-spring-boot-starter</artifactId>
</dependency>
<!-- Primefaces version 13.0.2 included -->
<dependency>
   <groupId>org.primefaces</groupId>
   <artifactId>primefaces</artifactId>
   <version>13.0.2</version>
</dependency>
<dependency>
   <groupId>org.primefaces.extensions</groupId>
   <artifactId>primefaces-extensions</artifactId>
   <version>13.0.2</version>
</dependency>
```
