### ISSUE TITLE
upgrade primefaces themes to 1.0.10

### ISSUE THREAD

**Issue by mtbadi39** [joinfaces/joinfaces#161]
<dependency>
            <groupId>org.primefaces.themes</groupId>
            <artifactId>all-themes</artifactId>
            <version>1.0.10</version>
        </dependency>
from

        <repository>  
            <id>primefaces-maven-repository</id>  
            <name>PrimeFaces Maven Repository</name>  
            <url>http://repository.primefaces.org</url>  
        </repository>

and switch between themes in application.yml

**Comment by persapiens** [comment]
@mtbadi39 , unfortynately all-themes 1.0.10 are not deployed at Maven Central. [Some Central Repository requirements](http://central.sonatype.org/pages/requirements.html) discourage using external repository. This same problem occurs with [testng 6.9.12](https://github.com/cbeust/testng/issues/1013)

Of course you can use all-themes 1.0.10 at your projects, excluding default version 1.0.8.

**Comment by mtbadi39** [comment]
> Of course you can use all-themes 1.0.10 at your projects, excluding default version 1.0.8.

Yeh, of course.

> unfortynately all-themes 1.0.10 are not deployed at Maven Central.

I just opened an issue for [that](https://github.com/primefaces/primefaces/issues/1653).

**Comment by persapiens** [comment]
So let's include this issue at [FAQ documentation](https://github.com/joinfaces/joinfaces/wiki/FAQ).

Thanks a lot.
