### ISSUE TITLE
Doesn't see the webapp when there are multiple modules.

### ISSUE THREAD

**Issue by GodFuper** [joinfaces/joinfaces#1670]
primefaces 4.7.5, Spring boot 2.7.5, Jetty.
Java 1.8, maven.
When you use multiple modules. *.xhtml and other resources are only taken from the webapp parent (root). 
How do I get index2.xhtml in resources?
![изображение](https://user-images.githubusercontent.com/40344333/219072464-e3d70d83-a54d-4084-b262-4c44aac155ed.png)

**Comment by larsgrefer** [comment]
One screenshot is not enough information about your project structure to see what is happening.

Can you upload an example project?

**Comment by GodFuper** [comment]
Sure, https://github.com/GodFuper/testMultiModule
I hope to find some simple solution to this problem. For example, write the path in application.properties or pom.xml and then everything will be fixed.

**Comment by larsgrefer** [comment]
The root project has it's `<packaging>` set to `pom`. That explains why `src/main/webapp` is ignored by maven and IntelliJ.

Your maven build has only one actual java web module, so that's the only one which is used.

Why would you expect this to work, and what exactly are you trying to do here?
