### ISSUE TITLE
Current Spring/Spring Boot Vulnerabilities: Please release JoinFaces 4.7.11 + 5.0.6!

### ISSUE THREAD

**Issue by chovyy** [joinfaces/joinfaces#1720]
Since there are some known vulnerabilities in the previous Spring and Spring Boot versions, I would appreciate if you can release the matching JoinFaces versions for the latest Spring Boot releases (2.7.11 + 3.0.6) as soon as possible.

See also https://spring.io/security, #1715, #1716.

**Comment by larsgrefer** [comment]
The releases should be available now

**Comment by chovyy** [comment]
Thanks a lot! :-)
