### ISSUE TITLE
phase-listener

### ISSUE THREAD

**Issue by gabsone** [joinfaces/joinfaces#174]
How to add a phase-listener  like this : 

```
<lifecycle>
  <phase-listener>com.ocpsoft.pretty.faces.event.MultiPageMessagesSupport</phase-listener>
</lifecycle>
```

Thanks

**Comment by persapiens** [comment]
Hi @gabsone ,

    If you use maven, include this configuration at src/main/resources/META-INF/faces-config.xml

You're welcome.

**Comment by persapiens** [comment]
This question goes to FAQ.
