### ISSUE TITLE
Blank page as no faces EL is resolved in page.

### ISSUE THREAD

**Issue by tejeshwar-p** [joinfaces/joinfaces#1761]
Hi Team, 
I have created as sample hello world application using joinfaces at - https://github.com/tejeshwar-p/jsf-with-spring-boot
I can get it to run but it is showing blank page.
Got the below info in logs which I suspect is the main problem for showing up blank page as none of the EL tags 
are resolved.

```j.e.resource.webcontainer.jsf.lifecycle  : JSF1027: [null] The ELResolvers for Faces were not registered with the Jakarta Server Pages container.```

Did not find any way to fix this. Need some help on it.
Please let me know any steps to resolve it. Am I missing any dependencies in pom.xml or any configuration in application.yml?

**Comment by larsgrefer** [comment]
Your xhtml file is made for JSF 4, but you are using JSF 3. Also you are missing a dependency on primefaces.

Use these dependencies to fix your project:

```xml
		<!-- joinfaces dependencies - start-->
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>faces-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>primefaces-spring-boot-starter</artifactId>
		</dependency>
		<!-- joinfaces dependencies - end-->
```

**Comment by tejeshwar-p** [comment]
Hi @larsgrefer, it was versioning mistake indeed.
Thank you for the resolution! I have updated the pom.xml with correct versions as suggested and now it is working as expected. 
Closing this issue. I want to release this basic quick start example [JSF 4 with Spring Boot 3.1.1](https://github.com/tejeshwar-p/jsf-with-spring-boot) to support join faces project. Please feel free to include this in your list of examples as required. 😊
