### ISSUE TITLE
Custom components are not rendered

### ISSUE THREAD

**Issue by rubiktubik** [joinfaces/joinfaces#188]
Hello i'm using your amazing joinfaces project but recently a encountered a strange behavior:

I followed the [tutorial](http://memorynotfound.com/jsf-custom-input-facescomponent-example/)  to create a Custom JSF component.

But when i want to use this component in my view nothing is showed.
In the rendered html it only shows: 
`<t:custom-input></t:custom-input>`

It seems that the component is not rendered!?

When i create the same component in a Netbeans Web project(which use an application server) it works
without a problem.

Do i need to configure something to get it to work?
Or why it is not working?

rubiktubik

**Comment by persapiens** [comment]
Hello @rubiktubik 

I've just create customInput page at joinfaces-example using the tutorial you've provided.
Take a look at https://github.com/joinfaces/joinfaces-example/issues/63

In favor of performance, JoinFaces only scan jsf types when the library contains faces-config.xml file.

Could you access http://localhost:8080/customInput.jsf to see customInput working?

Thanks in advance
marcelo

**Comment by rubiktubik** [comment]
Hello @persapiens 

Thank you for the fast answer and solution!

I added the faces-config.xml to my project and now the component is working without a problem!

Would be nice if one can configure the scan behavior in the application.properties ;-)

rubiktubik

**Comment by persapiens** [comment]
Hi @rubiktubik 

I agree that this solution is not ideal, but we have few options to configure scan with Reflections.

I've done some testing with [joinfaces-example](https://github.com/joinfaces/joinfaces-example) to show if we should remove such filtering with "faces-config.xml":

- when scanning only jars with "faces-config.xml" resource, Reflections takes around **0.33 seconds** to scan **6 jars**;
- when scanning all jars, Reflections takes around **1.70 seconds** to scan **110 jars**.

The second option adds **1.37 seconds** every application startup. It is very bad. The tradeoff is include faces-config.xml in your project when it includes jsf handled types.
