### ISSUE TITLE
Provide a joinfaces bom without spring-boot-dependencies

### ISSUE THREAD

**Issue by cachescrubber** [joinfaces/joinfaces#1974]
Currently the **joinfaces-dependencies** bom imports **spring-boot-dependencies** at the very end.

I'm maintainer of a central parent pom importing  **spring-boot-dependencies** and many other dependencies. When projects consuming the parent are importing **joinfaces-dependencies**, the latter will override the spring-boot version in use. Even more problematic, dependency overrides from the parent are overruled by the import of the joinfaces bom.

Could you imagine to publish a second bom artefact, excluding  **spring-boot-dependencies**?

**Comment by larsgrefer** [comment]
The biggest problem with this is to find suitable names for the - then two - JoinFaces BOMs 😅 

Technically we could have a BOM A which includes the joinfaces modules and dependencies like Primefaces and then a second BOM B which includes BOM A and `spring-boot-dependencies`.

For backward compatibility, it would make sense to name BOM B `joinfaces-dependencies` as it would behave like the current implementation, but what would be good name for the new BOM A?

**Comment by cachescrubber** [comment]
[Software developer thinking of a good name for a variable.](https://x.com/vlad_mihalcea/status/1711641927467118857) 😄 

For backward compatibility: How about `joinfaces-only-dependencies`?

**Comment by larsgrefer** [comment]
That tweet sums it up :D

Spring Framework has two artifacts:

framework-bom (only includes the spring artifacts itself)
framework-platform (includes dependencies and boms of other projects)

**Comment by jomu78** [comment]
What about "joinfaces-project-dependencies" for BOM A?

**Comment by persapiens** [comment]
If we follow Spring conventions.

**Comment by persapiens** [comment]
If we follow

**Comment by persapiens** [comment]
If we follow Spring Framework conventions, people may find JoinFaces artifacts easier.

**Comment by larsgrefer** [comment]
I've decided against backward compatibility and for (hopefully) better names:

The "old" `joinfaces-dependencies` is now `joinfaces-platform`
The "new" `joinfaces-dependencies` is now only contains external dependencies
`joinfaces-bom` only contains org.joinfaces artifacts.

I've also added a little diagram to the documentation to show the relationship between the different artifacts:
https://docs.joinfaces.org/5.2.x-SNAPSHOT/reference/#bom

**Comment by cachescrubber** [comment]
Good Choice - If it wasn't for backward compatibility I would have come up with the same structure.Thanks for your effort.

**Comment by cachescrubber** [comment]
Thanks @larsgrefer - I just updated an app to 5.2.0 using the new **bom** imports. Importing `joinfaces-bom` + `joinfaces-dependencies`  at the leaf of a dependency tree no longer overrides the spring-boot version and dependencies.
