### ISSUE TITLE
Could not release joinfaces 5.2.0-rc1

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#1975]
[Action 97](https://github.com/joinfaces/joinfaces/actions/runs/6613731596/job/17962163727) failed when I created joinfaces tag 5.2.0-rc1. Joinfaces 5.2.0-rc1 artifacts were not released:

`* What went wrong:
Task 'publishPlugins' not found in root project 'joinfaces-parent' and its subprojects.
`

**Comment by larsgrefer** [comment]
Fixed with 5.2.0-rc1.1 https://github.com/joinfaces/joinfaces/actions/runs/6632939124
