### ISSUE TITLE
Polish file upload with jetty & primefaces

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#202]
@nyilmaz , [your pull request](https://github.com/joinfaces/joinfaces/pull/195) fixes file upload with jetty & primefaces. More, there are no errors with tomcat and undertow before and after it.

Do you agree that this solution is specific to jetty? If positive, do you think we should move this code to specific [jsf-jetty-spring-boot-autoconfigure module](https://github.com/joinfaces/joinfaces/tree/master/jsf-jetty-spring-boot-autoconfigure)?

Just for your knowledge: i've changed [PrimefacesFileUploadServletContextAutoConfiguration class](https://github.com/joinfaces/joinfaces/blob/master/jsf-spring-boot-autoconfigure/src/main/java/org/joinfaces/primefaces/PrimefacesFileUploadServletContextAutoConfiguration.java) to work with myfaces too, changing @AutoConfigureAfter(**MojarraSpringBootAutoConfiguration.class**) to @AutoConfigureAfter(**JavaxFacesSpringBootAutoConfiguration.class**) .

 I can provide some test to keep test coverage later.

**Comment by nyilmaz** [comment]
@persapiens makes sense, however `FileUploadFilter` is from primefaces and is not registered automatically. jsf-jetty-spring-boot-autoconfigure module has not that primefaces dependency. So I did put that autoconfig class to  jsf-spring-boot-autoconfigure module (circular dependency issues).

Jetty or Spring somehow does not detect `FileUploadFilter` "automagically". Do you know how other servlet containers do so?

**Comment by nyilmaz** [comment]
That filter is required only if commons fileupload is chosen; see:

https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java#L33

`MultipartRequest ` is a wrapper which is applied only in `FileUploadFilter`.

**Comment by persapiens** [comment]
I don't know tomcat and undertow "automagically" works. However, "commons" option does not work with them, only native does. This situation does not change with your solution.

More, your "jetty" solution is generic enough, follows primefaces guidelines and works with "commons" and "native" options.

Following your explanation in this issue, I've just pushed minor changes at [PrimefacesFileUploadServletContextAutoConfiguration](https://github.com/joinfaces/joinfaces/blob/master/jsf-spring-boot-autoconfigure/src/main/java/org/joinfaces/primefaces/PrimefacesFileUploadServletContextAutoConfiguration.java) to create `PrimefacesFileUploadServletContextInitializer` and `FileUploadFilter` beans according to selected uploader (native or commons) option.

**Comment by nyilmaz** [comment]
@persapiens just fyi, similar setup is possible with adding jetty-annotations dependency and let jetty register `FacesServlet` as a `MultipartConfig` as such;

```
@Configuration
@EnableConfigurationProperties({JettyProperties.class})
@ConditionalOnClass(name = "org.eclipse.jetty.server.Server")
public class JettySpringBootAutoConfiguration extends SpringBootServletInitializer implements EmbeddedServletContainerCustomizer {

	@Autowired
	private JettyProperties jettyProperties;

	@Override
	public void customize(ConfigurableEmbeddedServletContainer container) {
		if (container instanceof JettyEmbeddedServletContainerFactory) {
			((JettyEmbeddedServletContainerFactory) container).addServerCustomizers(
				new JsfJettyServerCustomizer(this.jettyProperties));

			((JettyEmbeddedServletContainerFactory) container).addConfigurations(getConfiguration());
		}
	}

	private org.eclipse.jetty.webapp.Configuration getConfiguration() {
		return new AnnotationConfiguration();
	}
}
```

But in this way also we need to still register `FileUploadFilter` manually for primefaces. I guess **we may encourage users using native file upload since JSF 2.2 already has the implementation for parsing parts**. This solution is for jetty only because I know other servlet containers can register `FacesServlet` as a `MultipartConfig` with no additional configuration or dependency.

Anyway, I'm happy that case is solved :)

**Comment by persapiens** [comment]
Let 's keep this as another possibility. We could use it someday.

You a monster @nyilmaz . Thanks for sharing your accurate knowledge.
