### ISSUE TITLE
@FacesConverter classes are not being registered

### ISSUE THREAD

**Issue by sgornostal** [joinfaces/joinfaces#204]
I'm using org.joinfaces:jsf-jetty-spring-boot-starter version 2.2.7
My converter:

`
@FacesConverter(value = "zonedDateTimeConverter")
public class ZonedDateTimeConverter implements Converter {
....
}
`

And when I try to use it

`<f:converter converterId="zonedDateTimeConverter"/>`

I'm getting error:

`Expression Error: Named Object: zonedDateTimeConverter not found.`

Working fine if I define it through faces-config.xml
Probably related to #66

**Comment by persapiens** [comment]
Hi @sgornostal 

It is related to #66 and #188 . Just add faces-config.xml to your project.

**Comment by sgornostal** [comment]
@persapiens I have faces-config.xml file in my project with next content: 
```xml
<?xml version="1.0" encoding="utf-8"?>
<faces-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.jcp.org/xml/ns/javaee"
              xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
              http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd"
              version="2.2">
    <name>myapp</name>
    <application>
        <resource-bundle>
            <base-name>i18n/messages</base-name>
            <var>msg</var>
        </resource-bundle>
    </application>
</faces-config>
```

**Comment by persapiens** [comment]
Did you create it at src/main/resources/META-INF project folder?

**Comment by sgornostal** [comment]
yes, http://imgur.com/a/RLb9r

**Comment by persapiens** [comment]
I opened [this ticket](https://github.com/joinfaces/joinfaces-example/issues/81)  at [joinfaces example](https://github.com/joinfaces/joinfaces-example) to investigate this problem better.

If you mind, send one pull request: one page using one annotated converter is enough.

**Comment by persapiens** [comment]
just pushed initial example. it worked. missing some ui tests.
access converter page at http://localhost:8080/index.jsf?content=welcomeConverter

**Comment by sgornostal** [comment]
Just tested too, working well on the test project.
Any thoughts why it doesn't work on my project?

**Comment by persapiens** [comment]
Which joinfaces starter are you using?

**Comment by sgornostal** [comment]
jsf-jetty-spring-boot-starter: 2.2.7
spring-boot: 1.4.1.RELEASE

**Comment by sgornostal** [comment]
Can you try my test project?
https://github.com/sgornostal/jsf-test
I've just created and it doesn't work.

**Comment by persapiens** [comment]
try jsf-jetty-spring-boot-starter: 2.2.9 & spring-boot: 1.4.2.RELEASE

your converter class should be returned by find method of [JsfClassFactory.java](https://github.com/joinfaces/joinfaces/blob/master/jsf-spring-boot-autoconfigure/src/main/java/org/joinfaces/JsfClassFactory.java)

**Comment by persapiens** [comment]
The problem occurs because Gradle put java binaries and resources at different folders: build/classes/main and build/resources/main. faces-config.xml is at build/resources/main, however DateConverter.class is at build/classes/main. It does not happen with Maven because it put all of them under target/classes folder. 

If you run your app with `java -jar build/libs/jsftest-1.0-SNAPSHOT.jar`, it'll work.

It is time to create more generic approach!

**Comment by persapiens** [comment]
hi @sgornostal , I've just pushed one implementation to master branch. Could you build and test it in your application?

**Comment by sgornostal** [comment]
Hello, @persapiens . I've just tested. Works well. 
Thanks!

**Comment by persapiens** [comment]
Thanks for your contribution @sgornostal 
You are welcome.
