### ISSUE TITLE
How to generate a preparedScanResult?

### ISSUE THREAD

**Issue by jomu78** [joinfaces/joinfaces#2066]
On our docker / rancher environment the Classgraph Scan on startup takes quite long due to the resource limits we have enabled. While debugging the reason, I found in ServletContainerInitializerRegistrationBean the option, to load a pregenerated ScanResult from /META-INF/joinfaces/com.sun.faces.config.FacesInitializer.classes.

But I could not find out how to generate that list. Can you please assist?

**Comment by larsgrefer** [comment]
Up until JoinFaces 5.1 we have Maven and Gradle Plugins which perform the classpath scan at built-time:
https://docs.joinfaces.org/5.1.x/reference/#_build_tools_integration

Starting with JoinFaces 5.2 we have removed our own plugins and integrate with Spring AOT instead.

See https://github.com/joinfaces/joinfaces/discussions/1886 for more details

**Comment by jomu78** [comment]
We are currently migrating to SpringBoot 3.1 / JoinFaces 5.1 - the plugin works! Thanks for the hint. 

I am not yet into Spring AOT and just took a quick look into it yesterday. Something we have to dig into when migrating to JoinFaces 5.2...
