### ISSUE TITLE
Make JsfCdiToSpringApplicationContextInitializer implement Ordered interface

### ISSUE THREAD

**Issue by didiez** [joinfaces/joinfaces#213]
Would be great to be able to change the default order for `JsfCdiToSpringApplicationContextInitializer`.

In case you have other ApplicationContext that must be evaluater **after** `JsfCdiToSpringApplicationContextInitializer` you will find yourself in a dead end, since the default order is `Ordered.LOWEST_PRECEDENCE`, and obviously, there's no lower than the lowest :)

A simple fix for this would be make `JsfCdiToSpringApplicationContextInitializer` implement the `org.springframework.core.Ordered` interface and read the order value from properties, returning `Ordered.LOWEST_PRECEDENCE` as default value to keep backwards compatibility.

**Comment by persapiens** [comment]
hi @didiez , could you send us one pull request?

**Comment by didiez** [comment]
Sure, @persapiens any suggestion to name the key to specify the initializer order? 
Something like `jsf.integration.cdi-initializer.order` could make sense?

**Comment by persapiens** [comment]
yes, but what do you think about shorter ``jsf.cdi.initializerOrder`` ?

**Comment by didiez** [comment]
PR sent. 
I had to change the way it is the BeanFactoryPostProcessor registered to be able to load the actual property value configured.
However, I have mantained the config key as `jsf.cdi.initializerOrder`
Feel free to change the property key as there isn't an ApplicationContextInitializer no more (auto-configuration `@Configuration` class instead).
