### ISSUE TITLE
Could not resolve plugin artifact 'org.joinfaces:org.joinfaces.gradle.plugin:5.2.1'

### ISSUE THREAD

**Issue by triplemops** [joinfaces/joinfaces#2136]
joinfaces-5.2.1 is released but gradle plugin is only available in 5.2.0-m3

https://plugins.gradle.org/plugin/org.joinfaces
https://central.sonatype.com/artifact/org.joinfaces/joinfaces-gradle-plugin/versions

Could not use springboot-3.2.x then ;-(

**Comment by larsgrefer** [comment]
The Gradle Plugin is not necessary anymore for 5.2.x.

Just have a look at the reference documentation or the example projects:

https://docs.joinfaces.org/5.2.1/reference/#_gradle
https://github.com/joinfaces/joinfaces-gradle-jar-example/blob/e37006c7bf6358f253954080bda644762092c94a/build.gradle

**Comment by triplemops** [comment]
Ok, thanks. It works now!
