### ISSUE TITLE
 PrimeFaces Community Themes link if FAQ page leads to wrong page

### ISSUE THREAD

**Issue by Polve** [joinfaces/joinfaces#2238]
I'm new to the project and poking around, I see the link to "PrimeFaces Community Themes" in page 
https://github.com/joinfaces/joinfaces/wiki/FAQ brings you to https://www.primefaces.org/themes/ that gives a 404 error.

**Comment by larsgrefer** [comment]
Thanks for pointing this out.

The FAQ entry was written for an old prime faces version and is not applicable anymore so I removed it.
