### ISSUE TITLE
Usage without parent pom

### ISSUE THREAD

**Issue by martins-ka** [joinfaces/joinfaces#230]
Hi,

in my projects I'm using my own Maven parent pom, so it's not possible for me to use jsf-spring-boot-parent as parent. Is there an alternative way to use joinfaces? For example, Spring Boot provides spring-boot-dependencies as an alternative for dependencyManagement.

Thanks,
Martin

**Comment by persapiens** [comment]
Hi @martins-ka ,

Using joinfaces parent is optional. It reuses spring boot parent and enables some goodies like quality tools (firebug, checkstyle, pmd, cpd, duplicate code).

JoinFaces is a [set of spring boot starters to integrate JSF into Spring Boot](https://github.com/joinfaces/joinfaces/wiki/JSF-Spring-Boot-Starters). You should add one of them as dependency of your project.

[This example using maven](https://github.com/joinfaces/spring-boot-joinfaces) adds jsf-butterfaces-spring-boot-starter dependency to include tomcat, mojarra and butterfaces.

[This example using gradle](https://github.com/joinfaces/jsf-test) adds jsf-jetty-spring-boot-starter dependency to include jetty, mojarra and primefaces.

**Comment by martins-ka** [comment]
Thanks for your help, @persapiens! Works for me.
