### ISSUE TITLE
Typesafe Class parameters/properties

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#245]
Some JSF-properties are expecting a fully-qualified class name as their value.
How about using the Java type `Class<? extends T>` to represent this in the `@ConfigurationProperties`-classes.

## Example
`javax.faces.FACELETS_RESOURCE_RESOLVER` expects the name of an class which implements `javax.faces.view.facelets.ResourceResolver`. The current spring property in `JavaxFacesProperties` is defined as:

```java
private String faceletsResourceResolver;
```
this could be changed to:
```java
private Class<? extends ResourceResolver> faceletsResourceResolver;
```
## Advantages
- Better auto-completition in Spring-aware IDE's
- Fail-Fast behaviour: The spring context will not start if 
  - a given value is not a valid class name or if
  - the given class could not be loaded (not present in the JVM)

## Disadvantages
- Some base classes needed as generic-bound may not be present at compile-time or runtime:
  - Mojarra's `faceletFactory` Property needs a class extending `com.sun.faces.facelets.FaceletFactory`, but this class was only present in Mojarra 2.1 but is not present at 2.2

## More Examples:
- `org.joinfaces.javaxfaces.JavaxFacesProperties`
  - `faceletsResourceResolver`: `Class<? extends ResourceResolver>`
- `org.joinfaces.mojarra.MojarraProperties`
  - `serializationProvider`: `Class<? extends com.sun.faces.spi.SerializationProvider>`
  - `injectionProvider`: `Class<? extends com.sun.faces.spi.InjectionProvider>`
  - `expressionFactory`: `Class<? extends javax.el.ExpressionFactory>`
- `org.joinfaces.myfaces.MyfacesProperties`
  - `delegateFacesServlet`
  - `facesInitializer`
  - `serviceProviderFinder`
  - `elResolverPredicate`
  - `elResolverComparator`: `Class<? extends Comparator<ELResolver>>`

**Comment by persapiens** [comment]
Hi @larsgrefer , the advantages you've pointed are really good.

Is there any way to avoid or minimize the disadvantages? Split MojarraProperties into Mojarra21Properties and Mojarra22Properties?

**Comment by larsgrefer** [comment]
Hi @persapiens ,

as first step you could clarify which joinfaces versions are intended to work with which JSF versions, so all _old_ properties can be removed.

If I'm using one of the joinfaces starters I'd get Mojarra `2.2.x` which doesn't evaluate the `faceletFactory` parameter at all, so on the hand one could argue the corresponding property is useless. On the other hand it's possible to use the `autoconfigure`-module without a starter.

Given you want to keep the property (in case someone uses Mojarra `2.1.x`) the field could be defined without generic bounds:
```java
private Class<?> faceletFactory;
```
and a hint could be added to the `additional-spring-configuration-metadata.json`:
```json
{
    "name": "jsf.mojarra.facelet-factory",
    "providers": [
        {
            "name": "class-reference",
            "parameters": {
                "target": "com.sun.faces.facelets.FaceletFactory",
                "concrete": true
            }
        }
    ]
}
```

This way makes the java code a bit less type-safe an splits the information across two files but it's resistant against missing classes

**Comment by persapiens** [comment]
We should keep JoinFaces compatible with **JSF 2.0, 2.1 and 2.2**, because these versions are supported by PrimeFaces, BootsFaces, ButterFaces and RichFaces:

`PrimeFaces supports JSF 2.0, 2.1 and 2.2 runtimes at the same time using feature detection and by not having compile time dependency to a specific version. As a result some features are only available depending on the runtime. Apache MyFaces or Oracle Mojarra.`

`BootsFaces is targeted at Java EE 6/7 and requires a Java 1.6 or later VM. JSF 2.0, 2.1 and 2.2 are supported. BootsFaces supports Oracle Mojarra 2.2+ and Apache MyFaces 2.2+.`

`ButterFaces is a JSF 2 component enrichment framework. It wrappes most of default JSF 2 components and adds labels, readonly-views, tooltips, placeholder, validation style class marker and other nice features to the standard JSF 2 components.`

`RichFaces 4.5 has been developed and tested against both JSF 2.1 and 2.2. Go forth and take advantage of the new features available in JSF 2.2.`

**Comment by larsgrefer** [comment]
I'll start a PR for this, so we can see how it works

**Comment by larsgrefer** [comment]
@persapiens This is how the fail-fast behavior looks like:

```
00:54:23.160 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.joinfaces.myfaces.MyfacesProperties@263de070 failed:

    Property: jsf.myfaces.serialFactory
    Value: mySerialFactory
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'serialFactory'; nested exception is java.lang.IllegalArgumentException: Cannot find class [mySerialFactory]

    Property: jsf.myfaces.elResolverComparator
    Value: myResolverComparator
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'elResolverComparator'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myResolverComparator]

    Property: jsf.myfaces.elResolverPredicate
    Value: myResolverPredicate
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'elResolverPredicate'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myResolverPredicate]

    Property: jsf.myfaces.expressionFactory
    Value: myExpressionFactory
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'expressionFactory'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myExpressionFactory]

    Property: jsf.myfaces.delegateFacesServlet
    Value: myFacesServlet
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'delegateFacesServlet'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myFacesServlet]

    Property: jsf.myfaces.serviceProviderFinder
    Value: true
    Reason: Failed to convert property value of type 'java.lang.Boolean' to required type 'java.lang.Class' for property 'serviceProviderFinder'; nested exception is java.lang.IllegalArgumentException: Cannot convert value of type 'java.lang.Boolean' to required type 'java.lang.Class' for property 'serviceProviderFinder': PropertyEditor [org.springframework.beans.propertyeditors.ClassEditor] returned inappropriate value of type 'java.lang.Boolean'

    Property: jsf.myfaces.facesInitializer
    Value: myFacesInitializer
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Class' for property 'facesInitializer'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myFacesInitializer]

    Property: jsf.myfaces.facesInitPlugins
    Value: myInitPlugin
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.util.List' for property 'facesInitPlugins'; nested exception is java.lang.IllegalArgumentException: Cannot find class [myInitPlugin]

Action:

Update your application's configuration
```
