### ISSUE TITLE
List parameters/properties

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#248]
Some JSF-properties are expecting a list as their value (comma, semicolon or space separated).
How about using the Java type `List<T>` to represent this in the `@ConfigurationProperties`-classes.

## Example
`javax.faces.RESOURCE_EXCLUDES` expects a list of file-extensions.
The current Spring property is defined as:
```java
private String resourceExcludes;
```
this could be changed to:
```java
private List<String> resourceExcludes;
```
## Advantages
- same, Spring-like configuration syntax for all lists:
  - Before: comma, space or semicolon separated list
  - After: comma-separated or index-based
### Before
```properties
jsf.resourceExcludes=.gif .png .jpg
```
```yaml
jsf:
  resourceExcludes: .gif .png .jpg
```
### After:
```properties
jsf.resourceExcludes=.gif, .png, .jpg
```
```properties
jsf.resourceExcludes[0]=.gif
jsf.resourceExcludes[1]=.png
jsf.resourceExcludes[2]=.jpg
```
```yaml
jsf:
  resourceExcludes: .gif, .png, .jpg
```
```yaml
jsf:
  resourceExcludes:
    - .gif
    - .png
    - .jpg
```

## Disadvantages
The value in `application.properties` or `application.yml` might not be exactly the same like in `web.xml`

## More examples
- `org.joinfaces.javaxfaces.JavaxFacesProperties`
  - `resourceExcludes`: `List<String>`
  - `fullStateSavingViewIds`: `List<String>`
  - `faceletsLibraries`: `List<String>`
  - `faceletsViewMappings`
  - `configFiles`
- `org.joinfaces.myfaces.MyfacesProperties`
  - `facesInitPlugins`: `List<Class<?>>`

**Comment by persapiens** [comment]
`application.yml` usage should not be exactly the same like in `web.xml`. Using typed configuration instead of generic String is the right way in Spring Boot.

great job @larsgrefer .
