### ISSUE TITLE
Update checkstyle configs

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#251]
- upgrade to latest spring boot checkstyle configs.
- discuss some styles.

**Comment by persapiens** [comment]
@larsgrefer could you point your considerations?

I look forward your answer.

**Comment by larsgrefer** [comment]
I'll try to create code style settings for IntelliJ matching the checkstyle rules to make them less annoying

**Comment by larsgrefer** [comment]
see #254

**Comment by persapiens** [comment]
I'm not using idea. Are you confortable with the changes you've done? Is it necessary to change checkstyle configs now?

**Comment by larsgrefer** [comment]
I don't think changing the checkstyle configs is necessary anymore.

The major problems I had are solved.
