### ISSUE TITLE
Why is the auto-configuration code distributed across 5 modules?

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#255]
The project currently contains 5 modules with auto-configuration code:
- `jsf-spring-boot-autoconfigure`
- `jsf-tomcat-spring-boot-autoconfigure`
- `jsf-jetty-spring-boot-autoconfigure`
- `jsf-undertow-spring-boot-autoconfigure`
- `jsf-spring-boot-integration`

Why is this done this way?

Spring Boot uses one big auto-configure module instead

**Comment by persapiens** [comment]
I agree we could merge "step by step". 

`jsf-tomcat-spring-boot-autoconfigure`, `jsf-jetty-spring-boot-autoconfigure` and `jsf-undertow-spring-boot-autoconfigure` should be the latter, because when they were together some time ago, they have failed **war** packaging.

**Comment by larsgrefer** [comment]
>when they were together some time ago, they have failed *war* packaging.

#287 might fix this

**Comment by persapiens** [comment]
**war** packaging seems working. You did a great progress here @larsgrefer . 

What do you think about merging remaining jsf-spring-boot-integration artifacts into jsf-spring-boot-autoconfigure module? There are two things left:
- one faces-config.xml to configure JSF pages to read spring beans;
- code to enable spring security tags at JSF pages.

**Comment by larsgrefer** [comment]
The `faces-config.xml` is a very important key-component of _Joinfaces_, the _Spring Security_ taglib on the other hand is a rather optional addon. I can imagine usecases where one doesn't need or want the taglib, but a usecase without the `faces-config.xml` is hard to imagine.

How about putting the `faces-config.xml` into the `-autoconfigure`-module, but keeping the taglib code as separate module. (We could rename it from `jsf-spring-boot-integration` to `jsf-spring-security-taglib` or `spring-security-jsf-taglib`). The starters can still include both modules, but if someone doesn't want to use the taglib its easy to exclude using _Maven_/_Gradle_.

**Comment by persapiens** [comment]
I agree with you. Let's go with `spring-security-jsf-taglib`?
