### ISSUE TITLE
Add support for destroy methods in view scoped beans

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#256]

**Comment by persapiens** [comment]
Could you describe this enhancement a bit @larsgrefer ?

**Comment by larsgrefer** [comment]
Currently the _destroy methods_ (a.k.a. _destruction callbacks_) of view scoped beans are not called. For example methods annotated with `@PreDestroy`: http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-postconstruct-and-predestroy-annotations
