### ISSUE TITLE
Gradle example projects

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#260]
Hi @persapiens ,

I've created an repository containing example projects using grade and joinfaces: https://github.com/larsgrefer/joinfaces-gradle-example

Are you interested in hosting this under your joinfaces organization?

**Comment by persapiens** [comment]
I'm not very fluent with gradle yet. 

I've included a link to this repository at [Examples With.](https://github.com/joinfaces/joinfaces/wiki/Examples-of-JSF-Spring-Boot-Starter-usage)

As always thank you VERY MUCH.

**Comment by persapiens** [comment]
How do you think to do this? Just move the repository to joinfaces?

**Comment by larsgrefer** [comment]
The simplest option would be to transfer the ownership of the repository, so it becomes https://github.com/joinfaces/joinfaces-gradle-example

A more sophisticated option is to split the repository in 
`joinfaces/joinfaces-gradle-war-example` and `joinfaces/joinfaces-gradle-war-example`. In the same step you could rename the existing maven example repositories to match the same naming scheme, so we would get:
* `joinfaces/joinfaces-maven-jar-example`
* `joinfaces/joinfaces-maven-war-example`
* `joinfaces/joinfaces-gradle-jar-example`
* `joinfaces/joinfaces-gradle-war-example`

**Comment by persapiens** [comment]
I prefer the second option. I've just changed `joinfaces-example` to `joinfaces-maven-jar-example` and `joinfaces-war-example` to `joinfaces-maven-war-example`. I've updated these examples to use joinfaces 2.4.1 also.

More, war package run `inside` or `outside` servlet container. joinfaces-maven-war-example works `outside` servlet container with `java -jar joinfaces-maven-war-example.war`. Should we create another example to work `inside` servlet container or we could just comment how to do it? For example, configuration classes `inside` servlet container should extend SpringBootServletInitializer.

**Comment by larsgrefer** [comment]
If you create the corresponding `joinfaces-gradle-*-example` repositories and give me write permission on them, I'll fill them with the example projects.

My current Gradle war example can be used both inside and outside of an Servlet container.

**Comment by persapiens** [comment]
I've just created `joinfaces-gradle-jar-example` and `joinfaces-gradle-war-example` repositories. You are admin of both.

When you fill `joinfaces-gradle-war-example`, I will look at it carefully.

**Comment by larsgrefer** [comment]
@persapiens Could you enable travis for the 2 repositories?

**Comment by persapiens** [comment]
Of course, @larsgrefer. Travis enabled.

**Comment by larsgrefer** [comment]
Thanks.

The repositories are ready 👍

**Comment by persapiens** [comment]
I am out this week because [brazilian cbsoft](http://www.lia.ufc.br/~cbsoft2017/). I will learn a bit from gradle examples before closing this issue.
