### ISSUE TITLE
Support for JSF 2.3

### ISSUE THREAD

**Issue by gcameo** [joinfaces/joinfaces#268]
With JSF 2.3 now released, the JSF game is now really on!

http://arjan-tijms.omnifaces.org/2017/03/jsf-23-released.html

Any plans to support JSF 2.3?

**Comment by deki** [comment]
I've updated the Mojarra dependencies, MyFaces is not released yet.

**Comment by persapiens** [comment]
Hi @deki, I've discussed this issue [here.](https://github.com/joinfaces/joinfaces/pull/271)

**Comment by persapiens** [comment]
Initial support was merge #366

**Comment by persapiens** [comment]
JoinFaces 3.0.0.RC1 released with JSF 2.3 support.
Please open a new ticket if any issues appear.
