### ISSUE TITLE
Unable to determine how to define Omnifaces error pages for FullAjaxExceptionHandler

### ISSUE THREAD

**Issue by arvidj01** [joinfaces/joinfaces#270]
I am converting an old web application that uses Omnifaces. It defines the error page handlers in the web.xml file ...

```xml
<error-page>
    <error-code>500</error-code>
    <location>/common/errorPages/500.xhtml</location>
</error-page>
<error-page>
    <error-code>404</error-code>
    <location>/common/errorPages/404.xhtml</location>
</error-page>
...
```

as described for the [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler)

I'm not able to figure out how to put this into the application.yml file as I do not see anything related to it in the full [applicaiton.yml](https://github.com/joinfaces/joinfaces/blob/master/jsf-spring-boot-autoconfigure/src/test/resources/application.yml) nor do I see anything that might address it in what I think is the [relevant code](https://github.com/joinfaces/joinfaces/tree/master/jsf-spring-boot-autoconfigure/src/main/java/org/joinfaces/omnifaces).

Maybe I simply can not use the [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler)?

Or maybe there is more that I need to set in Spring Boot to use  the [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler)

Any help or a pointers to the documentation would be appreciated.

**Comment by larsgrefer** [comment]
@arvidj01 Have your tried to keep the `error-page` declarations in a `web.xml` or `web-fragment.xml` ?

**Comment by arvidj01** [comment]
First, thanks very much for the looking at this and responding.

I put the error page declarations in a web-fragment.xml file. It seems like Omnifaces is reading the file as I purposely left off a '>' and there was a stack trace generated about not being able to parse the file. From that I am assuming that Omnifaces is reading it.

I corrected the purposeful error but I am now facing what appears to be an issue with getting the [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler) to handle the errors. In the past I have used this in the faces-config.xml:

```xml
  <factory>
     <exception-handler-factory>org.omnifaces.exceptionhandler.FullAjaxExceptionHandlerFactory</exception-handler-factory>
  </factory>
```

I have this in the applications faces-config.xml but when I purposely try to go to a page that I know does not exit I get the "White Label" page rather than the page I mapped to with Omnipages. So I am still in the dark about how to properly configure things within joinfaces or Spring Boot or ??? to allow [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler) to handle exceptions.

Thanks for any help you can offer,
Arvid

**Comment by mtbadi39** [comment]
my be the solution provided [here](https://stackoverflow.com/questions/24730917/spring-security-session-timeout-handling-for-ajax-calls/31079774#31079774) helps : its about Timeout handling in Ajax calls.
