### ISSUE TITLE
Reflective Configuration not working with spring boot 1.5.3

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#281]
Joinfaces Example cannot read property `jsf.primefaces.theme = overcast` from application.yml when I use current master joinfaces after reflective configuration.

Could you take a look @larsgrefer ?

**Comment by larsgrefer** [comment]
Is there a failing test I could inspect?

**Comment by persapiens** [comment]
Tests are ok. Problem occurs when you use joinfaces-2.3.7-SNAPSHOT

Follow these steps, modifying joinfaces-example:

- Build joinfaces master version 2.3.7-SNAPSHOT
- change joinfaces-example pom.xml to use this snapshot
```xml
    <parent>
        <groupId>org.joinfaces</groupId>
        <artifactId>jsf-spring-boot-parent</artifactId>
        <version>2.3.7-SNAPSHOT</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```
- run / debug joinfaces-example

See that primefaces theme use default `aristo` value instead of `overcast` (configured at application.yml)

**Comment by larsgrefer** [comment]
I found the problem and will provide a PR.
