### ISSUE TITLE
What are the incompatibilities between joinfaces and primefaces 4

### ISSUE THREAD

**Issue by jkolobok** [joinfaces/joinfaces#293]
I have an old application which is written using primefaces 4. I'm trying to add spring support using joinfaces, but the app is not compatible with primefaces 6+, so I'm trying to avoid the upgrade.
What are the incompatibilities between joinfaces and primefaces 4?

**Comment by larsgrefer** [comment]
Which java and jsf version do you use?
Is Primefaces 5 an option for you?

**Comment by jkolobok** [comment]
java 8, jsf 2.2
No. primefaces 5.0 already has those incompatibilities.

**Comment by larsgrefer** [comment]
You won't be able to use the ```jsf.primefaces``` properties.

**Comment by larsgrefer** [comment]
@jkolobok Just give it a try

**Comment by larsgrefer** [comment]
@jkolobok Have you tried using joinfaces with primefaces 4?

**Comment by jkolobok** [comment]
Yes. From what I see now the theme configured through applications.properties doesn't get applied. There are probably some other issues. it's a lower priority task for now. I'll have more info in a week or so.

**Comment by larsgrefer** [comment]
Joinfaces 2.4.1 should work with Primefaces 4

**Comment by persapiens** [comment]
JoinFaces 2.4.1 has just been released. Could you verify it now @jkolobok please?

**Comment by persapiens** [comment]
Hi @jkolobok, I assume @larsgrefer solved the problem. If it is not the case, please reopen the issue.
