### ISSUE TITLE
Joinfaces 3

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#294]
~~Create a new branch for Joinfaces 3.x targeting Spring Boot 2.x and Spring Framework 5.x~~

Once the development of Joinfaces 3 starts, we should split up a `2.x` branch while 3 becomes the new `master`

The `2.x` versions should keep targeting Spring Boot 1.5.x and Spring Framework 4.x

**Comment by larsgrefer** [comment]
@persapiens What do you think?

* Which versioning and branching scheme should we use?
* Do we want to maintain 2 Versions of Joinfaces in parallell?

**Comment by persapiens** [comment]
I like `x.y.z` version scheme. It allows small and fast releases.
As you proposed, we could use `2.y.z` joinfaces versions for Spring Boot 1.5 and `3.y.z` joinfaces for Spring Boot 2.0.
We could maintain 2 versions of Joinfaces during some period, but we should concentrate our effort on joinfaces 3.
Spring Boot has just released 2.0.0.M2. Let's start this process about Spring Boot 2.0.0.M4 release ?

**Comment by larsgrefer** [comment]
@persapiens Do you know http://semver.org/ ?

**Comment by persapiens** [comment]
Thanks a lot for Semantic Versioning link.

Could we do something like [this](https://github.com/joinfaces/joinfaces/wiki/System-Requirements)?
