### ISSUE TITLE
Tests are running twice on travis

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#300]
Currently all the tests are running twice on travis.

1. in the second step of the `script`-phase while executing `./mvnw -T 2 -B --settings ignoreSnapshotsSettings.xml -Pignore-snapshot-repositories,check-cobertura-integration-test,attach-integration-test cobertura:check-integration-test` 
2. in the `after_success`-step while `./mvnw -B --settings ignoreSnapshotsSettings.xml -Pignore-snapshot-repositories,attach-integration-test cobertura:cobertura-integration-test org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report`

Can't `org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report` reuse the results from the first run?

**Comment by larsgrefer** [comment]
Cobertura can not check the the limits and generate a report in the same test-run. This is a huge drawback i think.

Have your ever considered using JaCoCo as code coverage tool?

**Comment by persapiens** [comment]
Cobertura was the first code coverage tool I've played with. It checks the limits and generate a report to coverage badge.
Could we do the same with JaCoCo?
