### ISSUE TITLE
Remove commons-fileupload dependency or wait 1.3.3 at maven central?

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#304]
Because of https://www.versioneye.com/java/commons-fileupload:commons-fileupload/1.3.2

**Comment by larsgrefer** [comment]
@persapiens `commons-fileupload` is only used by primefaces, right?

**Comment by persapiens** [comment]
Yes, because of commons option of fileupload. According to primefaces component, it is necessary only with Servlet 2.5 environment. In fact, joinfaces autoconfigure it, but it is not activated by default. It will be obsolete with spring boot 2.0 because it will require Servlet 3.1

**Comment by larsgrefer** [comment]
The only case in which you might need `commons-fileupload` with spring boot `1.4.x` or `1.5.x`
is when deploying a `war`-file to an old servlet-container like explained here: https://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#howto-servlet-2-5

On the other hand i see no problem with the dependency as long as it's `optional`

**Comment by persapiens** [comment]
done at #325
