### ISSUE TITLE
Reduce the starter count

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#306]
**Servlet Container**

I think it's unneccessary to have all our starters 3 times for different servlet containers. Our starters can simply depend on `org.springframework.boot:spring-boot-starter-web`. The servlet container can then be switched like described [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-jetty-instead-of-tomcat) and [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-undertow-instead-of-tomcat)

**JSF-Implementation**

It's also unneccessary to have all starters once for Mojarra and once for MyFaces. I think the choice between Mojarra and MyFaces should be done the same way like the choice between 
* Tomcat <> Undertow <> Jetty and between 
* Logback <> log4j2

*This would be a breaking change and should therefore be targeted at version 3.x*

**Comment by larsgrefer** [comment]
@persapiens What do you think?

**Comment by persapiens** [comment]
today, joinfaces user selects only one starter. However, we could follow "spring boot way" of creating starters.

there are some challenges that should be considered:
- using myfaces instead of mojarra forces including commons-digester dependency too;
- using jetty instead of tomcat forces including adding and removing other dependencies;
- using undertow instead of tomcat forces including adding and removing other dependencies;

How many joinfaces starters would remain?

**Comment by larsgrefer** [comment]
Basic implementation starters (each pulling `spring-boot-starter-web`):

* `mojarra-spring-boot-starter`
* `myfaces-spring-boot-starter` (pulls `commons-digester`)

Meta starters:
* `jsf-spring-boot-starter` (pulls mojarra by default. Like `spring-boot-starter-web` pulls tomcat and `spring-boot-starter-logging` pulls logback)

Basic component starters (each pulling `jsf-spring-boot-starter`):
* `omnifaces-spring-boot-starter`
* `primefaces-spring-boot-starter`
* `bootsfaces-spring-boot-starter`
* `butterfaces-spring-boot-starter`
* `richfaces-spring-boot-starter`
* `angularfaces-spring-boot-starter`

**Comment by persapiens** [comment]
I think I got your idea. We would have twelve starters:

Basic starters:

* `tomcat-spring-boot-starter` (pulls tomcat-embed-jasper)
* `jetty-spring-boot-starter` (pulls apache-jsp and spring-boot-starter-jetty)
* `undertow-spring-boot-starter` (pulls jboss-jsp-api_2.3_spec and spring-boot-starter-undertow)
* `mojarra-spring-boot-starter`
* `myfaces-spring-boot-starter` (pulls `commons-digester`)

Utility starters:
* `omnifaces-spring-boot-starter` (omnifaces is utility library and works with all of JSF component libraries)

Meta starters:
* `jsf-spring-boot-starter` (pulls `tomcat-spring-boot-starter`, `mojarra-spring-boot-starter`, `omnifaces-spring-boot-starter` and `spring-boot-starter-web`)

Component starters (each pulling jsf-spring-boot-starter):

* `primefaces-spring-boot-starter`
* `bootsfaces-spring-boot-starter`
* `butterfaces-spring-boot-starter`
* `richfaces-spring-boot-starter`
* `angularfaces-spring-boot-starter`

This issue will finish #342 .

Any considerations @larsgrefer ?

**Comment by persapiens** [comment]
@larsgrefer, I think we reduced joinfaces starters a bit. If you have any improvements, please open another issue.
