### ISSUE TITLE
is @RestController supported ???

### ISSUE THREAD

**Issue by it-sumanp** [joinfaces/joinfaces#313]
I created a controller but its returning 404 not found
when I hit http://localhost:8080/testme
> @RestController
@SpringBootApplication
public class JoinFacesExampleApplication {
    @RequestMapping("/testme")
    String home() {
        return "Hello World!";
    }
    protected JoinFacesExampleApplication() {
    }
}

**Comment by nyilmaz** [comment]
This may be a spring configuration issue. Have you checked your dependencies whether your application has spring mvc?

**Comment by it-sumanp** [comment]
I just edited the example application ..

yes it got spring web mvc from jsf-spring-boot-starter .

**Comment by it-sumanp** [comment]
Oh .. Sorry My Bad..
I forgot to add @EnableWebMvc on configuration class..
It is working now

**Comment by it-sumanp** [comment]
@nyilmaz  Thanks for Quick help
