### ISSUE TITLE
joinfaces-example-war don't compiler and don't running under tomcat

### ISSUE THREAD

**Issue by annorchen** [joinfaces/joinfaces#314]
1. If i checkout the current snapshot version (2.4.0-SNAPSHOT) i get a Exception in Eclipse IDE, that "Dynamic Web Module 3.1 requires Java 1.7 or newer." because Maven Compiler Plugin use 1.6 to build this project.

2. If I copy this war file to tomcat, it not started. The problem is, that JoinFacesExampleApplication don't extends SpringBootServletInitializer. I merge for me JoinFacesExampleApplication and JoinFacesExampleApplicationMain together like this:
```java
@SpringBootApplication
public class JoinFacesExampleApplication extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(JoinFacesExampleApplication.class);
	}

	public static void main(String[] args) {
		SpringApplication.run(JoinFacesExampleApplication.class, args);
	}

}
```

**Comment by larsgrefer** [comment]
I recommend you to use Java 7 or 8. If you really need to stay at Java 6, make sure to read this: http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#howto-use-java-6

**Comment by annorchen** [comment]
Hi Larsgrefer, yes, i use Java 8. I just want tell you, that your maven parent has config java 6 for this project.

**Comment by escanda** [comment]
I think it's much convenient to let users choose their java version, than to have to override.

You just have to set your properties like this:
```
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

**Comment by annorchen** [comment]
Yes, but if you use eclipse, you get this exception and can't build your project. And the secound problem is much more importent

**Comment by larsgrefer** [comment]
@escanda When working with `spring-boot-starter-parent` you should always use the `java.version` property in favor of `maven.compiler.source` and `maven.compiler.target`

@annorchen _Joinfaces_ (`jsf-spring-boot-parent`) and _Spring Boot_ (`spring-boot-starter-parent`) specify their `java.version` as `1.6` in order to produce Java 6 compatible `.class`-Files.
Just add this to your `pom.xml`:
```xml
<properties>
    <java.version>1.8</java.version>
</properties>
```

**Comment by larsgrefer** [comment]
@annorchen Can we close this issue? Or do you still have questions or problems?

**Comment by annorchen** [comment]
@larsgrefer for 1. problem i solution it. but 2. is still open

**Comment by chapus** [comment]
Same issue here.
