### ISSUE TITLE
Location of XHTML files

### ISSUE THREAD

**Issue by t-oster** [joinfaces/joinfaces#315]
Hi. In the examples the xhtml-files are located in `src/main/resources/META-INF/resources`. When developing with NetBeans this is not detected as Webapp folder, so its under **Other Sources** which seems wrong.

Other JSF project seem to have the files under `src/main/webapp` which seems more natural and NetBeans also shows this as **Web Pages** folder. If I run a project from NetBeans it works fine, but if I try to run the generated jar, the files are not found.

Do I need to configure the folder somewhere or do the sources have to be under `src/main/resources/META-INF/resources`?

**Comment by larsgrefer** [comment]
Can't you tell NetBeans that `src/main/resources/META-INF/resoures` is a web root?

If you wan't to use `src/main/webapp` as web root, you can use _Joinfaces_/_Spring Boot_ with `war`-packaging:
https://github.com/joinfaces/joinfaces-example-war
https://github.com/larsgrefer/joinfaces-gradle-example/tree/master/war-example

**Comment by t-oster** [comment]
Thank you for your answer. If I find out how to tell NetBeans to interpret src/main/resources/META-INF/resoures without creating a custom project-type, I will post it here. War packaging is not an option, since I want to use the executable jar file as daemon.

**Comment by larsgrefer** [comment]
The `war`-file can be run via `java -jar`, too

**Comment by t-oster** [comment]
Thank you, but I am talking about running the jar as native linux executable with /etc/init.d

**Comment by larsgrefer** [comment]
This should work with war packaging too

**Comment by t-oster** [comment]
Hmm.. I tried to convert it to war packaging, but I did not succeed.. However I agree that it may be a netbeans specific problem. So if there is no easy way to change the location of the xhtml files inside joinfaces, the best way would be to update netbeans to recognize the path as web-folder.
