### ISSUE TITLE
cache resource files

### ISSUE THREAD

**Issue by macnal** [joinfaces/joinfaces#322]
In the demo application "joinfaces-example" the resource files are not cached. The cache-control directive in header response is set by the server on `Cache-Control: no-cache, no-store, max-age=0, must-revalidate`
Is there a way that the resource files from `/javax.faces.resource/*` was cached?

**Comment by larsgrefer** [comment]
@macnal Are you using Spring Security in your project? Spring Security sets this header value as default.

- https://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html
- http://www.baeldung.com/spring-security-cache-control-headers

**Comment by macnal** [comment]
You're right, thank you

**Comment by elab** [comment]
updated link to Spring Security doc: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#headers-cache-control
