### ISSUE TITLE
Change "jsf-spring-boot-X" module name to "joinfaces-X"

### ISSUE THREAD

**Issue by persapiens** [joinfaces/joinfaces#342]
This project was initially named "JSF Spring Boot Starter" before named "Joinfaces". The source code is under `org.joinfaces`, but module names are still using `jsf-spring-boot-X` conversion.

We could rename four libraries:
* `jsf-spring-boot-autoconfigure` -> `joinfaces-autoconfigure`
* `jsf-spring-boot-parent` -> `joinfaces-parent`
* `jsf-spring-boot-starters` -> `joinfaces-starters`
* `jsf-spring-boot-test` -> `joinfaces-test`

Joinfaces starters could be changed also. If we follow spring boot starters naming conventions:
* `jsf-bootsfaces-spring-boot-starter` -> `joinfaces-starter-bootsfaces`
* `jsf-butterfaces-spring-boot-starter` -> `joinfaces-starter-butterfaces`
* `jsf-jetty-bootsfaces-spring-boot-starter` -> `joinfaces-starter-jetty-bootsfaces`
* `jsf-jetty-butterfaces-spring-boot-starter` -> `joinfaces-starter-jetty-butterfaces`
...
* `jsf-spring-boot-starter` -> `joinfaces-starter`
...
* `jsf-undertow-spring-boot-starter` -> `joinfaces-starter-undertow`

Changing Joinfaces starters naming will force users to adapt `pom.xml` dependency artifactId.

**Comment by larsgrefer** [comment]
Should'nt the starter for `butterfaces` named `butterfaces-spring-boot-starter`?

The reference documentation says:
>Let’s assume that you are creating a starter for "acme", name [...] the starter `acme-spring-boot-starter`.

**Comment by persapiens** [comment]
@larsgrefer, I merged before reading your comment. Sorry.

Official Spring Boot Starters start with `spring-boot-starter` **prefix**. However, reference documentation says [Community Contributions](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters) to use `spring-boot-starter` as our **suffix**.

So, what will be joinfaces starter suffix name: `spring-boot-starter`, `jsf-spring-boot-starter`, or `joinfaces-spring-boot-starter`?

1. `spring-boot-starter` suffix. We have two options: starters name stay the same, or change `jsf` prefix to `joinfaces`. Here, `jsf-butterfaces-spring-boot-starter` becomes `joinfaces-butterfaces-spring-boot-starter` and `jsf-spring-boot-starter` becomes `joinfaces-spring-boot-starter`.

1. `jsf-spring-boot-starter` suffix. We remove `jsf` prefix: `jsf-butterfaces-spring-boot-starter`  becomes `butterfaces-jsf-spring-boot-starter` and `jsf-spring-boot-starter` remains unchanged.

1. `joinfaces-spring-boot-starter` suffix. We have two options: remove `jsf` prefix. Here, `jsf-butterfaces-spring-boot-starter` becomes `butterfaces-joinfaces-spring-boot-starter` and `jsf-spring-boot-starter` becomes `joinfaces-spring-boot-starter`. The second option is stay `jsf` prefix. So, `jsf-butterfaces-spring-boot-starter` becomes `jsf-butterfaces-joinfaces-spring-boot-starter` and `jsf-spring-boot-starter` becomes `jsf-joinfaces-spring-boot-starter`. 

I prefer option 1: `spring-boot-starter` suffix changing `jsf` prefix to `joinfaces`. My second preference is `joinfaces-spring-boot-starter` suffix removing `jsf` prefix.

What do you prefer?

**Comment by persapiens** [comment]
I've just merged starters implementation according to #306 discussion.
