### ISSUE TITLE
startup fails with spring-boot 2.0.0.M4

### ISSUE THREAD

**Issue by mbakhoff** [joinfaces/joinfaces#345]
Starting a Spring Boot 2.0.0.M4 application fails if `org.joinfaces:jsf-spring-boot-starter:2.4.1` is included in maven dependencies.

Spring console:
```
WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [sample.Application]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/context/embedded/EmbeddedServletContainerCustomizer.class] cannot be opened because it does not exist
```

Looks like it's caused by `org.joinfaces.jetty.JettySpringBootAutoConfiguration` implementing `org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizer` which no longer exists. 

Trivial sample application: https://github.com/mbakhoff/joinfaces-sample

**Comment by mbakhoff** [comment]
Ah, looks like https://github.com/joinfaces/joinfaces/pull/341 is working on it

**Comment by Philmasteryeah** [comment]
@mbakhoff 
I think there is something wrong in your pom.xml
clone the joinfaces git and run the "mvnw.cmd install"
change your pom like this [https://github.com/Philmasteryeah/joinfaces-boot-jetty-cdi/blob/master/pom.xml](url)
then it should work properly

**Comment by mbakhoff** [comment]
@Philmasteryeah 
I'm pretty sure my pom.xml is fine. The application starts up normally if I replace spring boot version 2.0.0.M4 with 1.5.8.RELEASE. It also starts up normally with spring boot 2.0.0.M5 + joinfaces 3.0.0-SNAPSHOT. Simply the current stable release of joinfaces doesn't support spring boot 2.x. Let me know if I missed anything. Thanks!

**Comment by persapiens** [comment]
You are right @Philmasteryeah. JoinFacex 3.x will support Spring Boot 2.x. JoinFaces 2.x remains with Spring Boot 1.5.x.

More information [about versions](https://github.com/joinfaces/joinfaces/wiki/System-Requirements).

Note that JoinFaces 3.x will have a [new set of starters](https://github.com/joinfaces/joinfaces/wiki/JoinFaces-Starters-3.x). You could see it working in [JoinFaces Maven Jar Example](https://github.com/joinfaces/joinfaces-maven-jar-example).

**Comment by persapiens** [comment]
Hi @Philmasteryeah ,

JoinFaces 3.0.0.RC1 released with Spring Boot 2.x support.
Please open a new ticket if any issues appear.

**Comment by lucksjb** [comment]
I try update my application to springboot 2.0.1-RELEASE and  joinfaces jsf-spring-boot-starter 3.1.0;
and application run, but datatable with filterby dont working.

If I using springboot 1.5.10.RELEASE and joinfaces jsf-spring-boot-starter 2.4.1, this running ok ... (but I had writed a TomcatContainerConfig class)...
