### ISSUE TITLE
jsf.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL not working

### ISSUE THREAD

**Issue by anaq1** [joinfaces/joinfaces#347]
I'm trying to set jsf.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL property, so empty strings are interpreted as null. But it doesn't work. 
I can see the context parameter is set to true:
```
// this returns string "true"
FacesContext.getCurrentInstance().getExternalContext().getInitParameter("javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL");
```

I have created simple test maven project - one parent (with jsf-spring-boot-parent dependency) and one web (with jsf-spring-boot-starter dependency) with latest joinfaces (2.4.1), Java 8. These projects have only joinfaces dependencies, no other.

application.properties:
```
jsf.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=true
```

Application.java:
```
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }   
}
```

TestBean.java:
```
@ManagedBean
@ViewScoped
@Component
public class TestBean {
    private Test entity = new Test();
    public void save() {
        System.out.println("Test : " + entity.getText());       // entity.getText() is always ""
    }
    public Test getEntity() {return entity;}
    public void setEntity(Test entity) {this.entity = entity; }    
}
```

test.xhtml:
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui">
    <h:body>
        <h:form id="form">            
            <p:inputText value="#{testBean.entity.text}"/>            
            <p:commandButton action="#{testBean.save}"/>
        </h:form>
    </h:body>
</f:view>
```

As a workaround a custom ElResolver can be used, it's described here: http://balusc.omnifaces.org/2015/10/the-empty-string-madness.html

**Comment by persapiens** [comment]
Hi @anaq1,

If you say that the code above returns string "true"

```java
FacesContext.getCurrentInstance().getExternalContext().getInitParameter("javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL");
```

when application.properties has this value
```properties
jsf.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=true
```

So it means that JoinFaces configured JSF properly.

I used this property with [JoinFaces Example](https://github.com/joinfaces/joinfaces-maven-jar-example) and it returned **null** as expected.
