### ISSUE TITLE
How to config and customize servlet mapping

### ISSUE THREAD

**Issue by royandray** [joinfaces/joinfaces#356]
On my project. The url mapping is .xhtml. How to config the servlet mapping to map the .xhtml?

**Comment by persapiens** [comment]
hi @royandray,

By default, JSF URL mapping is .xhtml.

**Comment by beleta** [comment]
> By default, JSF URL mapping is: "/faces/", ".jsf", ".faces", ".xhtml"

This is true for Mojarra but not for MyFaces. So the question is still valid.

**Comment by classicPintus** [comment]
That mapping creates a problem with the jsf resources. A css for example, if doesn't contains one of the default jsf url mappings is not recognized.
In the joinfaces example, the url of all the resources ends with ".jsf", even if they're images, js, css

**Comment by persapiens** [comment]
Hi @classicPintus , could you try current master and see if you can customize servlet mapping using `jsf.faces-servlet` properties?

**Comment by classicPintus** [comment]
Yes, I'm starting now

**Comment by dmitry-naumovich** [comment]
Hello, how can I override FacesServlet mapping with Spring Boot 1.5.22.RELEASE and Joinfaces 2.4.1? 
I try to register beans this way:
`   

    @Bean
    @Primary
    public ServletRegistrationBean facesServletRegistration() {
        ServletRegistrationBean registration = new ServletRegistrationBean(facesServlet(), "*.html");
        registration.setName("FacesServlet");
        registration.setLoadOnStartup(0);
        return registration;
    }

    @Bean 
    @Primary
    public FacesServlet facesServlet() {
        return new FacesServlet();
    }




`
but it doesn't work, I get the next logs:

`{"@timestamp":"2021-12-28T11:09:19.664+02:00","@version":"1","message":"Mapping servlet: 'FacesServlet' to [*.html]","logger_name":"o.s.b.w.s.ServletRegistrationBean","thread_name":"localhost-startStop-1","level":"INFO"}
{"@timestamp":"2021-12-28T11:09:19.665+02:00","@version":"1","message":"Servlet FacesServlet was not registered (possibly already registered?)","logger_name":"o.s.b.w.s.ServletRegistrationBean","thread_name":"localhost-startStop-1",
"level":"INFO"}
`
