### ISSUE TITLE
Best practices for error page mapping in joinfaces

### ISSUE THREAD

**Issue by dos7** [joinfaces/joinfaces#367]
Hello,

we're developing a web application with embedded tomcat, spring-boot (no mvc) and joinfaces. We don't have a web.xml nor a web-fragment.xml, so error page mapping is a bit difficult.  We implemented error mapping as a `@Bean` annotated method in a `@Configuration` class. 
E.g.:

    @Bean
        public ErrorPageRegistrar errorPageRegistrar() {
            return new ErrorPageRegistrar() {
                @Override
                public void registerErrorPages(ErrorPageRegistry registry) {
                    registry.addErrorPages(new ErrorPage(HttpStatus.NOT_FOUND, errorPage));
                    registry.addErrorPages(new ErrorPage(HttpStatus.INTERNAL_SERVER_ERROR, errorPage));
                }
            };
        }

Where `errorPage` is a static variable that points to the error file. Classes like [FacesExceptionFilter](http://showcase.omnifaces.org/filters/FacesExceptionFilter) or [FullAjaxExceptionHandler](http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler) from Omnifaces unfortunately do not work (since we do not have a web.xml).
So is this approach really the best way to implement error page mapping in joinfaces or is there a better solution available?

**Comment by nyilmaz** [comment]
I think you can use `FilterRegistrationBean` to register `FacesExceptionFilter` or extend it if you want to customize its behaviour.

**Comment by dos7** [comment]
That totally worked thank you! 
Do you know something about our other problems?

**Comment by slamalotfi1987** [comment]
Hello dos 7 
i m trying to handle errors in springboot/primefaces project 
can you help me with a exemple (how to use a FilterRegistrationBean to handle 404 or 500 exception)??

**Comment by dos7** [comment]
Hi slamalotfi1987,

sure. First set up a configuration class and add a mapping method like the following:

    import org.springframework.boot.web.servlet.ErrorPage;
    import org.springframework.boot.web.servlet.ErrorPageRegistrar;
    import org.springframework.boot.web.servlet.ErrorPageRegistry;
    import org.springframework.boot.web.servlet.FilterRegistrationBean;
    import org.omnifaces.filter.FacesExceptionFilter;
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.Configuration;
    import org.springframework.http.HttpStatus;
   
    @Configuration
    public class JsfConfig {

    private final String yourErrorPage = "/error/error.xhtml";
    
    //FilterRegisBean with FacesExceptionFilter
    @Bean
    public FilterRegistrationBean filterRegisBean() {
        final FilterRegistrationBean filterRegBean = new FilterRegistrationBean();
        filterRegBean.setFilter(new FacesExceptionFilter());
        filterRegBean.addUrlPatterns("/*");
        filterRegBean.setEnabled(Boolean.TRUE);
        return filterRegBean;
    }
    
    //ErrorPageRegistration, mapping method
    @Bean
    public ErrorPageRegistrar errorPageRegistrar() {
        return new ErrorPageRegistrar() {
            @Override
            public void registerErrorPages(ErrorPageRegistry registry) {
                registry.addErrorPages(new ErrorPage(HttpStatus.NOT_FOUND, yourErrorPage));
                registry.addErrorPages(new ErrorPage(HttpStatus.INTERNAL_SERVER_ERROR, yourErrorPage));
            }
        };
    }

    } 

`yourErrorPage` should point to a XHTML file, which should be displayed, when the error occurred (for example in META-INF/resources/error/error.xhtml).
Sorry for the bad formatting of the code.

**Comment by slamalotfi1987** [comment]
think you  man for the answer that will be helpfull ,just i want to know:with your method can we don't work with web.xml file???

**Comment by dos7** [comment]
if you're working with an embedded container the web.xml or web-fragment.xml file would be ignored (see https://github.com/spring-projects/spring-boot/issues/2175)

**Comment by mtbadi39** [comment]
Hi,
**Spring Boot** provide that out of the box, see docs [here](https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#boot-features-error-handling).

**Comment by philipreimer** [comment]
Hi @mtbadi39, 

could you elaborate a bit what you mean by "out-of-the-box"?
The docs you linked seem to be targeting spring-mvc.
But the question was about using JSF with spring boot.
Or am I missing something in the docs?

Thanks in advance

**Comment by mtbadi39** [comment]
Hi @philipreimer 

> Or am I missing something in the docs?

I think yes : [this](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-error-handling-custom-error-pages) and [this](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-error-handling-mapping-error-pages-without-mvc)

Also the solution provided in @nyilmaz and @dos7 comments works for me :

> its about using **FilterRegistrationBean** to register **FacesExceptionFilter** or extend it if you want to customize its behaviour

Alse, the idea in [this example](https://stackoverflow.com/questions/24730917/spring-security-session-timeout-handling-for-ajax-calls/31079774#31079774) my help, its for Timeout handling in Ajax calls.

**Comment by ollbap** [comment]
I was to configure error handing for primefaces using joinfaces and spring-boot 2. Ir order for it to work I extended the PrimeExceptionHandlerFactory to override the method  that decides where the error page is according to the thrown exception. This extended error handler is defined on src/main/resources/META-INF/faces-config.xml.

This is quite a hack, is would be great if joinfaces could configure this when primefaces is detected, error handling is required in order to create a JSF aplication with primefaces.

Complete working project can be found at: https://github.com/ollbap/my-primefaces-spring-boot-skeleton

See: 
  * https://github.com/ollbap/my-primefaces-spring-boot-skeleton/blob/master/src/main/resources/META-INF/faces-config.xml
  * https://github.com/ollbap/my-primefaces-spring-boot-skeleton/blob/master/src/main/java/es/test/config/ExtendedPrimeExceptionHandlerFactory.java

**Comment by melloware** [comment]
@ollbap The answer given by @dos7 is much more flexible and comprehensive using OmniFaces exception handling and is much cleaner than this approach.  And it allows you to map multiple error pages so Security Exception can go to 403.xhtml and Unauthorized can go to 401.xhtml etc.  

Your solution looks like it sends all errors to 1 error page?

**Comment by ollbap** [comment]
This was just provided as a working example using the approach explained in the primefaces documentation (11.3 Exception Handler at the primefaces user guide). In fact, the definitions on the faces-config.xml also are required for the component p:ajaxExceptionHandler to work.

In order to handle other exceptions you can just return the desired page at ExtendedPrimeExceptionHandlerFactory.java on the evaluateErrorPage() method. This is even more flexible that just mapping the exception class at a map since the have the actual thrown exception.

I don't know how to apply the @dos7 solution since there is no FacesExceptionFilter equivalent for primefaces, just the PrimeExceptionHandlerFactory is documented.

**Comment by melloware** [comment]
You can either use OmniFaces which has that FullExceptionHandler. or look at the OmniFaces code and copy and make a similar Exception Filter.

**Comment by inkarnadin** [comment]
> I don't know how to apply the @dos7 solution since there is no FacesExceptionFilter equivalent for primefaces, just the PrimeExceptionHandlerFactory is documented.

Add filter yourself. Worked for me.

    @Component
    public class FacesExceptionFilter extends OncePerRequestFilter {        

        @Override
        @SneakyThrows({IOException.class, ServletException.class})
        public void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) {
            filterChain.doFilter(request, response);
        }
    }
