### ISSUE TITLE
Reflections URL Issue

### ISSUE THREAD

**Issue by hMounir** [joinfaces/joinfaces#372]
First of all, using joinfaces has been a blast for me, and I really liked using it but now I face a problem about classes scanning when I try to deploy on Oracle Weblogic 12c, I experience a long deployment time, (over 8 minutes long), so when I debugged through the code, I saw that the class org.joinfaces.JsfClassFactory from the autoconfigure project loads two additional URLS that's not related to the application at all. like this:
/oracle/WLS_1221/oracle_common/modules/oracle.jps/
/oracle/WLS_1221/user_projects/domains/base_domain/

I don't know why is that, as a workaround, I have overridden the class on my project removed these urls manually, so can you please help me figure out the real cause of the issue,

**Comment by persapiens** [comment]
hi @hMounir ,

Is this issue relevant to you?

I look forward your answer.

**Comment by persapiens** [comment]
@hMounir, I will close this issue. Of course, you can reopen it if you want.
