### ISSUE TITLE
How to redirect the user to a custom error page when session expires

### ISSUE THREAD

**Issue by dos7** [joinfaces/joinfaces#373]
Hello,

we've tried to implement a redirection to a custom session expired page, but several attempts did not work properly. The webapp just redirects to the login page. 

Attempts we've tried:

- `http.sessionManagement().maximumSessions(1).expiredUrl("/error/expired.xhtml");` (in addition [spring security - expiredUrl not working](https://stackoverflow.com/a/36974952/8944690))
- Error Page mapping to ViewExpiredException (does not work, since this exception is never thrown in our application. When session is expired a AccessDeniedException is thrown by Spring Security, but we can not (neither do we want to) map a error page to this exception, since it's not only thrown when the session expires)

Does anyone know a solution for this problem?

**Comment by mtbadi39** [comment]
my be [this](https://stackoverflow.com/questions/24730917/spring-security-session-timeout-handling-for-ajax-calls/31079774#31079774) help

**Comment by dos7** [comment]
Thanks @mtbadi39! Your suggestion gave us the right hint to come up with a solution for our problem. I will post the solution, in case anybody encounters the same issues. We implemented a custom `SessionTimeoutFilter` like this:

    @Slf4j
    public class SessionTimeoutFilter extends GenericFilterBean {

        private final static String AJAX_REDIRECT_XML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<partial-response>" +
                "<redirect url=\"%s\"></redirect>" +
                "</partial-response>";

        private final AuthenticationTrustResolver authenticationTrustResolver;
        private final JsfConfig jsfConfig;

        public SessionTimeoutFilter(final JsfConfig jsfConfig) {
            Assert.notNull(jsfConfig, "JsfConfig must NOT be null!");
            this.jsfConfig = jsfConfig;
            authenticationTrustResolver = new AuthenticationTrustResolverImpl();
        }

        @Override
        public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain)
                throws IOException, ServletException {

            if ((request instanceof HttpServletRequest) && (response instanceof HttpServletResponse)) {
                final HttpServletRequest httpServletRequest = (HttpServletRequest) request;
                final HttpServletResponse httpServletResponse = (HttpServletResponse) response;

                // is session expire control required for this request AND is session invalid?
                if (isSessionControlRequiredForThisResource(httpServletRequest) &&          
    authenticationTrustResolver.isAnonymous(SecurityContextHolder.getContext().getAuthentication())) {

                    final String redirectPage = httpServletRequest.getContextPath() + jsfConfig.getLoginPage();
                    log.debug("Session invalid, redirection initiated...");

                    setErrorMessageInSession(httpServletRequest);

                    if (isAJAXRequest(httpServletRequest)) {
                        createAjaxResponse(response, httpServletResponse, redirectPage);
                    } else {
                        httpServletResponse.sendRedirect(redirectPage);
                    }

                    return;
                 }
            }
            filterChain.doFilter(request, response);
        }

        private void createAjaxResponse(final ServletResponse response,
                                        final HttpServletResponse httpServletResponse,
                                        final String redirectPage) throws IOException {
            log.debug("Ajax call detected, XML redirection triggered...");
            httpServletResponse.setHeader("Cache-Control", "no-cache");
            httpServletResponse.setCharacterEncoding("UTF-8");
            httpServletResponse.setContentType("text/xml");
            final PrintWriter pw = response.getWriter();
            pw.printf(AJAX_REDIRECT_XML, httpServletResponse.encodeRedirectURL(redirectPage));
            pw.flush();
        }

       private void setErrorMessageInSession(HttpServletRequest httpServletRequest) {
            final HttpSession session = httpServletRequest.getSession(true);
            if (session != null) {
                // The exception's message property contains key for error message from 
    localization.properties
                session.setAttribute(WebAttributes.AUTHENTICATION_EXCEPTION, new 
    SessionTimeoutException("expired.description"));
            }
        }

        /**
         * The session shouldn't be checked for some pages. For example: the expired page, root page, etc.
         * If we do not disable it on these specific pages, it would result in an infinite loop. Returns true, if 
         * session control is needed, false otherwise.
         */
        private boolean isSessionControlRequiredForThisResource(final HttpServletRequest 
    httpServletRequest) {
            final String requestPath = httpServletRequest.getRequestURI();
            return !requestPath.contains(jsfConfig.getLoginPage()) &&
                    !requestPath.contains(jsfConfig.getResourcesLocation()) &&
                    !requestPath.equals(jsfConfig.getRootPage());
        }

        /**
         * Checks whether the current HttpServletRequest is a Ajax Request. Return true if so,
         * false otherwise.
         */
        private boolean isAJAXRequest(final HttpServletRequest request) {
            final String facesRequest = request.getHeader("Faces-Request");
            return "partial/ajax".equals(facesRequest);
        }

    }
