### ISSUE TITLE
Rewrite Config

### ISSUE THREAD

**Issue by arturveiga** [joinfaces/joinfaces#390]
I have a small problem when using Rewrite, it does not create the customizable url, and it neither enters the getConfiguration () method, when calling "/panel/visitante/consulta",
it returns a 404.
help guys

`@RewriteConfiguration 
public class AccessRewriteConfiguration extends HttpConfigurationProvider {     
 @Override 
public int priority() {         return 10;     }      
@Override     
public Configuration getConfiguration(ServletContext context) {          return ConfigurationBuilder.begin()                 .addRule(Join.path("/").to("/index.xhtml")).                         addRule(Join.path("/panel/visitante/consulta").to("/pages/private/visitante/consulta.xhtml"));      } }`

**Comment by larsgrefer** [comment]
closing this in favor of #392

**Comment by arturveiga** [comment]
After you suffer a bit trying to create friendly URLs. Getting to ride with pretty faces, is a bit rustic but in the first tests, it turned out well...

`@Bean
    public FilterRegistrationBean prettyFilter() {
        FilterRegistrationBean registration  = new FilterRegistrationBean(new RewriteFilter());
        registration .setDispatcherTypes(DispatcherType.FORWARD, DispatcherType.REQUEST, 
        DispatcherType.ASYNC,
                DispatcherType.ERROR);
        registration .addUrlPatterns("/*");
        return registration ;
    }`

`@Override
    public void onStartup(ServletContext servletContext)
            throws ServletException {

        servletContext.setAttribute("com.ocpsoft.pretty.CONFIG_FILES",new PrettyConfigCustom());
    }`

`public class PrettyConfigCustom extends PrettyConfig {
    @Getter
    @Setter
    private List<UrlMapping> mappings = new ArrayList();

    public PrettyConfigCustom() {
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setId("dashboard");
        urlMapping.setPattern("/");
        urlMapping.setViewId("/index.jsf");
        UrlMapping urlMapping2 = new UrlMapping();
        urlMapping2.setId("pagina");
        urlMapping2.setPattern("/pagina");
        urlMapping2.setViewId("/pagina.jsf");
        mappings.add(urlMapping);
        mappings.add(urlMapping2);

    }


}`
