### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by arturveiga** [joinfaces/joinfaces#392]
how to use prettyfaces in joinfaces?

**Comment by larsgrefer** [comment]
Joinfaces does not have special prettyfaces support, but using [rewrite](https://www.ocpsoft.org/rewrite/) should work out of the box

**Comment by arturveiga** [comment]
@larsgrefer. I tested rewrite, my project only uses 2 starters, jsf and spring boot, but rewrite did not work, it did not map the url.

**Comment by larsgrefer** [comment]
Can you share your project with us, so we can have a look?

**Comment by arturveiga** [comment]
https://github.com/arturveiga/demo-joinfaces

**Comment by larsgrefer** [comment]
It seems like Rewrite can't handle the jar-layout and/or the embedded tomcat.

Could you try a war-project and maybe deploying to an existing servlet container?

**Comment by didiez** [comment]
Rewrite can handle jar-layout without problems. I've integrated several applications using this layout.
Here's a simple auto-configuration 
```java

@Configuration
public class RewriteAutoConfiguration {
   
    @Bean
    public RewriteServletRequestListener rewriteServletRequestListener(){
       return new RewriteServletRequestListener();
    }
   
    @Bean
    public RewriteServletContextListener rewriteServletContextListener(){
        return new RewriteServletContextListener();
    }
   
    @Bean
    public FilterRegistrationBean rewriteFilterRegistrationBean() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new RewriteFilter());
        registration.setDispatcherTypes(EnumSet.allOf(DispatcherType.class));
        registration.addUrlPatterns("/*");
        return registration;
    }
    
}
```

**Comment by arturveiga** [comment]
@didiez, how did you map your url's?

**Comment by didiez** [comment]
Placing annotations on my beans. https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/configuration/annotations/index.asciidoc#defining-rules-with-annotations

**Comment by persapiens** [comment]
@didiez, 

HttpConfigurationProvider classes [like this](https://github.com/arturveiga/demo-joinfaces/blob/master/src/main/java/com/example/demo/config/ExampleConfigurationProvider.java) works with the auto configuration that you have provided too? Or it works only with annotations beans? 

Anyway, I think rewrite is an excellent fellow to JSF. 

Would you mind creating `rewrite-spring-boot-starter` using the auto configuration you have written?

You could follow [these steps](https://github.com/joinfaces/joinfaces/wiki/Creating-Spring-Boot-Starter-to-specific-JSF-component-library) to create it.

Rewrite have some [configuration properties also.](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/configuration/annotations/index.asciidoc#configuration)

I look forward your answer.

**Comment by didiez** [comment]
Sure, I will give it a try as soon as I have some spare time.

**Comment by arturveiga** [comment]
After you suffer a bit trying to create friendly URLs. Getting to ride with pretty faces, is a bit rustic but in the first tests, it turned out well...

```
@Bean
    public FilterRegistrationBean prettyFilter() {
        FilterRegistrationBean registration  = new FilterRegistrationBean(new RewriteFilter());
        registration .setDispatcherTypes(DispatcherType.FORWARD, DispatcherType.REQUEST, 
        DispatcherType.ASYNC,
                DispatcherType.ERROR);
        registration .addUrlPatterns("/*");
        return registration ;
    }
@Override
    public void onStartup(ServletContext servletContext)
            throws ServletException {

        servletContext.setAttribute("com.ocpsoft.pretty.CONFIG_FILES",new PrettyConfigCustom());
    }

public class PrettyConfigCustom extends PrettyConfig {
    @Getter
    @Setter
    private List<UrlMapping> mappings = new ArrayList();

    public PrettyConfigCustom() {
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setId("dashboard");
        urlMapping.setPattern("/");
        urlMapping.setViewId("/index.jsf");
        UrlMapping urlMapping2 = new UrlMapping();
        urlMapping2.setId("pagina");
        urlMapping2.setPattern("/pagina");
        urlMapping2.setViewId("/pagina.jsf");
        mappings.add(urlMapping);
        mappings.add(urlMapping2);

    }
}
```
Someone with higher knowledge than I can have an idea to improve the code, thank you from the bottom of the heart. <3

**Comment by arturveiga** [comment]
att. https://github.com/arturveiga/demo-joinfaces

**Comment by persapiens** [comment]
hi @arturveiga ,

Happy to see it working. Your demo mix [rewrite implementation with prettyfaces configuration](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/migration/prettyfaces3.asciidoc). You use "PrettyFaces XML and Annotations" method. It is [one method to active rewrite configuration](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/configuration/install.asciidoc#3-activate-your-configuration). 

> Note: Alternate methods of configuration are available, such as Rewrite Annotations, PrettyFaces XML and Annotations, and via cdi and spring; these methods may be used to avoid the need for a provider registration file.

@didiez uses "Rewrite Annotations" method.

Starting with [Weld Spring Boot Starter](https://github.com/joinfaces/joinfaces/pull/391), we could  investigate [cdi integration.](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/integration/cdi.asciidoc)

Of course, we should investigate [spring integration](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/integration/spring.asciidoc) also.

**Comment by persapiens** [comment]
I'm writing [rewrite-spring-boot-starter](https://github.com/persapiens/joinfaces/tree/rewrite) using code provided by @didiez and @arturveiga . Some findings:

| Configuration | Result | Observation |
| --- | --- | ---|
| @ RewriteConfiguration Annotation | **failed** | does not work with jar packaging because rewrite way of scanning classes. So, it can't find ConfigurationProvider implementation. |
| /META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider | **ok** | configuration works well. |
| Rewrite Annotations | **ok** | according to @didiez comments above |
| PrettyFaces XML and Annotations | **ok** | according to @arturveiga comments above |
| CDI | **not tested** | |
| Spring | **ok** | provided by joinfaces autoconfiguration classes. |

I'll do more tests before merging code.

**Comment by Tosken1337** [comment]
Ithave problem get rewrite working using annotation configuration.
Id does not pick up the annotation.
What am i doing wrong?

**Comment by persapiens** [comment]
hi @Tosken1337 ,

Could you show an example?

I look forward your answer.
