### ISSUE TITLE
Upgrade to Spring Boot 2.0

### ISSUE THREAD

**Issue by mtbadi39** [joinfaces/joinfaces#405]
[Spring Boot 2.0 is now generally available](https://spring.io/blog/2018/03/01/spring-boot-2-0-goes-ga)

**Comment by persapiens** [comment]
Hi @mtbadi39 ,

It is already in [master](https://github.com/joinfaces/joinfaces/pull/389).

We are going to release joinfaces 3.0.0 next friday.
