### ISSUE TITLE
Initialization NoSuchMethodError in JsfClassFactory

### ISSUE THREAD

**Issue by alissongodoi** [joinfaces/joinfaces#422]
Hi there,

I was brining the project up and I get the following error:

Caused by: java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.setExpandSuperTypes(Z)Lorg/reflections/util/ConfigurationBuilder

The method setExpandSuperTypes does not exist anymore in the Reflections Lib being pulled.

http://static.javadoc.io/org.reflections/reflections/0.9.10/org/reflections/util/ConfigurationBuilder.html

This comes from the computeClasses()

```
	private void computeClasses() {
		this.annotatedClassMap = new HashMap<>();
		this.otherClassMap = new HashMap<>();

		TypesHandled handlesTypes = handlesTypes();
		// check if any type is handled
		if (!handlesTypes.isEmpty()) {
			// create reflections
			Reflections reflections = new Reflections(new **ConfigurationBuilder().setExpandSuperTypes(false)**.setUrls(getURLs()));

			// add types annotated for each type to be handled
			for (Class<? extends Annotation> annotationType : handlesTypes.getAnnotationTypes()) {
				this.annotatedClassMap.put(annotationType, reflections.getTypesAnnotatedWith(annotationType));
			}
			// add subtype of other types to be handled
			for (Class<?> otherType : handlesTypes.getOtherTypes()) {
				this.otherClassMap.put(otherType, (Set<Class<?>>) reflections.getSubTypesOf(otherType));
			}
		}
	}
```

**Comment by alissongodoi** [comment]
I found the issue. Querydsl was overwriting to an old lib.
I excluded this from Querydsl and letting spring security to handle it.
		<dependency>
		    <groupId>org.reflections</groupId>
		    <artifactId>reflections</artifactId>
		    <version>0.9.11</version>
		</dependency>

**Comment by persapiens** [comment]
Hi @alissongodoi,

I think this issue is not related to joinfaces. If so, could you close this issue?

I look forward your answer.
