### ISSUE TITLE
Richfaces reached it's end of life

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#463]
Richfaces reached it's end of life in 2016: https://developer.jboss.org/wiki/RichFacesEnd-Of-LifeQuestionsAnswers

How long do we want to support it?

**Comment by persapiens** [comment]
Does anyone use it here?

If not, we could drop support this year.

**Comment by eirslett** [comment]
I tried to look at porting a very old codebase (Spring framework 2.x, JSF, Richfaces, Webflow) to Spring Boot, and it looks like joinfaces would help a lot!

**Comment by larsgrefer** [comment]
Our Richfaces support isn't that complicated. It currently would'nt harm us to keep it.

On the other hand: If we'd drop support for Richfaces, you could easily re-implement in your project.
