### ISSUE TITLE
Primefaces fileUpload tag does not work as showcased

### ISSUE THREAD

**Issue by Pankiev** [joinfaces/joinfaces#471]
I tried to use **<p:fileUpload />** tag as showcased [here](https://www.primefaces.org/showcase/ui/file/upload/multiple.xhtml)

When i click the button to choose file the system file chooser pop-ups like expected, but when i choose file the gui does not react, and no backing bean method is invoked.

When i open browser's console (chrome in this case) i can see an error, which is printed on page load.

```
Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at qa (http://localhost:8080/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=6.2:3:6636)
    at Function.r.parseHTML (http://localhost:8080/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=6.2:4:18781)
    at new r.fn.init (http://localhost:8080/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=6.2:2:25517)
    at r (http://localhost:8080/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=6.2:2:601)
    at http://localhost:8080/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=6.2:2:448
    at http://localhost:8080/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=6.2:2:198
    at http://localhost:8080/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=6.2:2:217
```

Configuration is same as in #457, except joinfaces version is now 3.2.0 (which didn't actually change anything in terms of this bug)

I have found also some other primefaces' tags that does not work properely before.
I could not find any solution online, could this be related to joinfaces?

**Comment by persapiens** [comment]
hi @Pankiev ,

Could you provide a demo example?

I look forward your answer.

**Comment by Pankiev** [comment]
@persapiens I have managed to find what causes this its 
`jsf.mojarra.prefer-xhtml=true`
in application.properties, removing it solves problems with other tags also, so it is probably not related to joinfaces. You can close this one. 
Sorry for taking your time.

**Comment by persapiens** [comment]
@Pankiev, it can be related to mojarra. Did you test myfaces or other mojarra version?

**Comment by Pankiev** [comment]
@persapiens I didn't and i really wouldn't like to, but I made [repo](https://github.com/Pankiev/Showcase) with simple application that reproduces this bug.  If you're really interested, just run it and open on http://localhost:8080/views/showcase-upload.xhtml

I also added showcase-textarea.xhtml, where a p:inputTextarea tag is used and it does not autosize as it should.
