### ISSUE TITLE
Build failed with joinfaces 3.2.1 - error in pom

### ISSUE THREAD

**Issue by WalterMourao** [joinfaces/joinfaces#483]
Hi folks. Jut upgraded to 3.2.1 and I've got:

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /home/walter/.m2/repository/org/joinfaces/joinfaces-dependencies/3.2.1/joinfaces-dependencies-3.2.1.pom: end tag not allowed in epilog but got / (position: END_TAG seen ...</distributionManagement>\n</project>\n</... @885:3)  @ /home/walter/.m2/repository/org/joinfaces/joinfaces-dependencies/3.2.1/joinfaces-dependencies-3.2.1.pom, line 885, column 3

```
Thanks,
Walter

**Comment by larsgrefer** [comment]
@WalterMourao Please try to delete joinfaces from your local maven repository (`rm -r /home/walter/.m2/repository/org/joinfaces/`) and try to build your project again.

**Comment by WalterMourao** [comment]
@larsgrefer thanks. It is working fine now.

**Comment by balram8264** [comment]
Anyone please give solution to fix it. org.apache.maven.model.io.ModelParseException: end tag not allowed in epilog but got / (position: END_TAG seen ...                                                                </... @528:130)
