### ISSUE TITLE
Selenium Tests

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#494]
Hi,

we want to use selenium's webdriver to perform integration tests of the jsf pages.
We follow the joinfaces example's and using the PageObject pattern to lookup components on the page and perform actions.
The problem is, that we are using spring security and thus we have to login first before we can load the pages to test.
Can we somehow mock a test with a specific user?
Spring provides a way to do this using @WithMockUser.
But i think this only works when testing with Spring's MockMvc.

Spring also provides a way to use MockMvc with the selenium webdriver (https://spring.io/blog/2014/03/26/spring-mvc-test-with-webdriver).
But in this case the jsf pages will not be processed. I think mockmvc only uses the default dispatch servlet.

Thanks for help

**Comment by larsgrefer** [comment]
Have you already tried using `@WithMockUser`?

**Comment by larsgrefer** [comment]
I have two Ideas you can try:

1. Use BasicAuth

**Comment by Tosken1337** [comment]
Yes i tried this.
But creating a mockmvc does not work with joinfaces and java server pages setup.
MockMvc only uses the DispatchServlet and thus a get request results in returning unprocessed xhtml jsf page.

**Comment by persapiens** [comment]
Hi @Tosken1337 ,

[joinfaces-maven-jar-example](https://github.com/joinfaces/joinfaces-maven-jar-example) does not mock user, but it [tests login](https://github.com/joinfaces/joinfaces-maven-jar-example/blob/master/src/test/java/org/joinfaces/example/view/LoginPageIT.java).
