### ISSUE TITLE
JSF 2.3 CDI of context vars not working

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#495]
Hi,

i tried to use the injection of jsf objects which were introduced in jsf 2.3.

For example using

`@Inject
@SessionMap
private Map<String, Object> sessionMap;`

in a Bean annotated with `@Named` is not working.

**Comment by larsgrefer** [comment]
@Tosken1337 please try `@Qualifier("sessionMap")` instead of `@SessionMap`

**Comment by Tosken1337** [comment]
Thanks
