### ISSUE TITLE
Primefaces Dialog Framework

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#498]
Hi,

i am not able to use the primefaces dialog framework.
A commandButton will trigger an bean action method to programmaticaly open a dialog like this

`PrimeFaces.current().dialog().openDynamic("editDeviceDialog",
                options,
                params
                );`

The function will be called but primefaces did not show any dialog or logging an error.
Did i miss somenthing?
The primefaces documentation wrotes that some listeners needs to be configured in the faces-config.xml.

Even when i add a faces-config.txt in the META-INF/resources folder with the suggested content it will not work.

**Comment by larsgrefer** [comment]
I've just tried the dialog framework on one of our example projects, and it seems to work fine.

You provide an example project, which reproduces your problem?

**Comment by Tosken1337** [comment]
The <p:dialog> element is also working fine in my project but the Framework do open dialogs programmatically will just insert a div in the page but it is hidden and empty.
I will upload a demo project.
Which example project did you checkout?

**Comment by Tosken1337** [comment]
I have created a new clean test project and now i at least get an error message in the chrome console when opening the dialog:
Refused to display ....  in a frame because it set 'X-Frame-Options' to 'deny
Think that is because the dialog framework uses iframes to inject the dialog.
How can i handle this?

**Comment by larsgrefer** [comment]
@Tosken1337 Can we close this issue?
