### ISSUE TITLE
class file for javax.inject.Qualifier not found

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#505]
After upgrading to Joinfaces 3.2.2 (or 3.2.3) I get the following error when trying to compile my application:

error: cannot access Qualifier
  class file for javax.inject.Qualifier not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for javax.inject.Qualifier not found

Is this a bug in Joinfaces or am I missing something?

**Comment by persapiens** [comment]
hi @bjorntj ,

Just add javax.enterprise:cdi-api dependency to your app. See details in #503

**Comment by bjorntj** [comment]
Aaah... I did not read the release notes for 3.2.3 properly.... :-|
Thx...

**Comment by bjorntj** [comment]
But it's kind of strange since I do not use inject features.. But I guess some other dependencies are using it...

**Comment by persapiens** [comment]
Could you provide a sample project to reflect this issue?

**Comment by bjorntj** [comment]
I can see if I can manange that... :)

**Comment by bjorntj** [comment]
Hmmm.. Not that easy I see... Not able to reproduce it in my little test project.
But I am using both Flyway and JOOQ in my other project. I guess one of them uses the inject feature...

**Comment by persapiens** [comment]
In this case, these libraries should pull all dependencies they need to work properly.

**Comment by bjorntj** [comment]
Yes, they should.. But discovered that this was not the problem. Tried to upgrade a different project where I am not using Flybase or JOOQ but still got the same error.
Will see if I can find the time in the near fututre, to start stripping a project to pinpoint where this error comes from.
