### ISSUE TITLE
Mojarra ajax response which contains CDATA does not update anymore

### ISSUE THREAD

**Issue by hammadirshad** [joinfaces/joinfaces#506]
Mojarra ajax response which contains CDATA does not render anymore. 

<h:outputScript>
/* <![CDATA[ */

    ...code...

/*  ]]> */
</h:outputScript>

**Comment by persapiens** [comment]
Hi @hammadirshad ,

Could you provide a sample project to check it?
More, you could downgrade mojarra to see if it is related to joinfaces or mojarra itself.

I look forward to your answer.


More, did

**Comment by hammadirshad** [comment]
Sorry this is Mojarra related issue.

https://github.com/javaserverfaces/mojarra/issues/4370
