### ISSUE TITLE
How to handle ViewExpiredException ?

### ISSUE THREAD

**Issue by av-git** [joinfaces/joinfaces#513]
Hi 
How to handle ViewExpiredException ?

**Comment by av-git** [comment]
and how would you do in joinfaces?

**Comment by persapiens** [comment]
hi @av-git ,

Take a look at the discussion in #367.

**Comment by larsgrefer** [comment]
@av-git Can you provide some more information abour your concrete problem?

**Comment by av-git** [comment]
my aplication "joinfaces" does not treat ViewExpiredException.
I would like to know how to configure

**Comment by av-git** [comment]
?

**Comment by larsgrefer** [comment]
What do you want to configure exactly?
In which cases do you get a `ViewExpiredException`?
How and where do you expect the Exception to be handled?

**Comment by rmpestano** [comment]
Can you try this JoinFaces starter?
https://github.com/adminfaces/admin-starter-springboot

I think it has what you're looking for.

It uses AdminFaces, if you don't want to use It you can extract the exception handler that handles the ViewExpired in AdminFaces.

I hope it helps.

**Comment by av-git** [comment]
very good.
