### ISSUE TITLE
 Problem in Converter with JSF version 2.3.3

### ISSUE THREAD

**Issue by juliocesarsantos1020** [joinfaces/joinfaces#514]
A partir da versão 3 do JoinFaces, o converter mostra essa mensagem **Erro de validação: o valor não é válido** pelo fato de estar utilizando a versão Mojarra 2.3.3, nesta versão o Converter sofreu algumas modificações.

Atualizei para versão 2.4.1, funcionou perfeitamente, percebi que nesta versão do JoinFaces, é utilizado a versão Mojarra 2.2.14.

Parabéns pelo trabalho @persapiens, está me ajudando e muito. #

**Comment by persapiens** [comment]
hi @juliocesarsantos1020 ,

    Glad to see joinfaces helps you.
    Please post your issue in English. So, more people may help.
    Could you post one example project?

I look forward to your answer.

**Comment by juliocesarsantos1020** [comment]
No problem, my friend.

Tonight I'm going to upload a project for you to validate.

**Comment by juliocesarsantos1020** [comment]
Hi @persapiens 
As promised by me, here is a project that will produce the error that I commented.
https://github.com/juliocesarsantos1020/example-joinfaces

Note the error message:
sourceId=frmPerson:j_idt13[severity=(ERROR 2), summary=(frmPerson:j_idt13: Erro de validação: o valor não é válido), detail=(frmPerson:j_idt13: Erro de validação: o valor não é válido)]

**Comment by juliocesarsantos1020** [comment]
Hi @persapiens ! 

Did you see that question?

**Comment by larsgrefer** [comment]
After changing the database to h2 and manually saving a "state" instance in the database i can reproduce the error

**Comment by larsgrefer** [comment]
`StateService.findByIdState()` called in `StateConverter.getAsObject()` returns `Optional<State>`

**Comment by juliocesarsantos1020** [comment]
Hi @larsgrefer!
Thanks, I forgot to return the object this way state.get
