### ISSUE TITLE
how to configure language and location for pt BR?

### ISSUE THREAD

**Issue by av-git** [joinfaces/joinfaces#527]
how to configure language and location for pt BR ?

**Comment by larsgrefer** [comment]
Can you please describe your specific problem?

**Comment by av-git** [comment]
JoinFaces internationalization example

**Comment by larsgrefer** [comment]
I still don't understand your problem.

**Comment by mtbadi39** [comment]
There are tons of examples on the net, just [google it](https://www.google.dz/search?q=jsf+internationalization&oq=jsf+internationalization) !

**Comment by larsgrefer** [comment]
Im closing this issue now.

If you still have problems, please open a new issue with a detailed explanation and an example project which repoduces the problem

**Comment by persapiens** [comment]
hi @larsgrefer ,

Why don't ask for a `test case or sample application` in `all` issues at [ISSUE_TEMPLATE.md](https://github.com/joinfaces/joinfaces/blob/master/.github/ISSUE_TEMPLATE.md)? JoinFaces run in many environments, I always need an specific environment setup to understand the issue.

If you agree, we could move the following explanation to be available to all kinds of issues: Question, Bug Report or Enhancement
```
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
```
