### ISSUE TITLE
Order of resource loading

### ISSUE THREAD

**Issue by dihoti** [joinfaces/joinfaces#530]
Is it possible to determine the order in which SpringBoot is loading resources?
I have XHTML files in libraries (under META-INF/resources) that I want to override in the actual project, where I also place the XHTML files under META-INF/resources). In the package jar file SpringBoot seems to read the resource in the jar file under BOOT-INF, first, and the project resources under META-INF later.
Is there any way to influence the loading behaviour or just to override resources from jar files??

**Comment by larsgrefer** [comment]
The classloader which is set up for repackaged jar files (`org.springframework.boot.loader.LaunchedURLClassLoader`) uses the order of the entries in the jar file.

The repackage functions of the maven and gradle plugins ensure that the application classes (`src/main/resources`) are stored before the dependencies:

https://github.com/spring-projects/spring-boot/issues/12263

**Comment by larsgrefer** [comment]
@dihoti Can we close this issue?
