### ISSUE TITLE
How to inject a request parameter

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#548]
Hi,

how can i inject a request parameter into the bean?
My beans are using spring's @Component annotation togehter with the annotations for the scope.
Currently i use the <f:viewParam> jsf tag to bind the request parameters to the fields of my bean.

Sinse for omnifaces @param injection a full CDI is necessary, we don't want to use this.

I already tried @Inject together with @Named or @ManagedAttribute, but none of this is working.
Did i miss something?

Injections of FacesContext variables is done with a custom joinfaces bean postprocessor, is that correct?

And is it possible to inject a list as parameter? For example pass a comma seperated string as param and inject them as a list of strings?

I think this is possible using the jsf ManagedAttribute annotation like `@ManagedProperty(value = "#{param[ids]}")`

Thanks a lot

**Comment by larsgrefer** [comment]
Hi,

``<f:viewParam />`` is the default way to do this.

As alternative to this, you could try this:

```java
@Autowired // or @Inject
@Qualifier("param") // or @javax.faces.annotation.RequestMap
private Map<String, String> params;
```

or this:

```java
@Value("#{param['ids']}")
private String ids;
```

**Comment by larsgrefer** [comment]
@Tosken1337 Is your issue solved?
