### ISSUE TITLE
from 3.2.4 to 3.2.5 "Looking for @ControllerAdvice" is missing

### ISSUE THREAD

**Issue by StevenHachel** [joinfaces/joinfaces#549]
Hello,

there will be no @RestController "actuator, error, ..." and my own more initialized.

**Comment by larsgrefer** [comment]
The joinfaces starters stopped to pull `spring-boot-starter-web` (and therefore `spring-mvc`) because `spring-webmvc` is not necessary for JSF.

If you are using _Spring Web MVC_ (Dispatcher Servlet, RestController, etc.) you have to add a dependency on `spring-boot-starter-web` to your project.

**Comment by StevenHachel** [comment]
it works again! Many many thx! :-)
