### ISSUE TITLE
Whitelabel Error Page - Spring Security

### ISSUE THREAD

**Issue by juliocesarsantos1020** [joinfaces/joinfaces#563]
I'm not using tomcat from spring, I'm using another one, and this error is always appearing when I try to log in.

Whitelabel Error Page

This application has no explicit mapping for / error, so you are seeing this as a fallback.
Wed Oct 17 20:56:50 BRT 2018
There was an unexpected error (type = Not Found, status = 404).
No message available

**Comment by juliocesarsantos1020** [comment]
Here's my sample project.

https://github.com/juliocesarsantos1020/example-joinfaces


can you help me? @persapiens , @larmic , @jamillosantos

**Comment by larsgrefer** [comment]
@juliocesarsantos1020 I'll have a look at the project.

Some first thoughts:
- Pointing to a specific JDBC URL is a bad Idea for example projects. Whoever tries to run the example is unlikely to have a corresponding database running.
- Publishing the JDBC password is even worse

**Comment by juliocesarsantos1020** [comment]
@larsgrefer.

Sorry, my friend, this is not going to happen anymore.

**Comment by juliocesarsantos1020** [comment]
@persapiens 

So my project was developed based on the JoinFaces Maven War Example, the only difference being that I do not use the tomcat embedded Spring

**Comment by juliocesarsantos1020** [comment]
@larsgrefer 

Many thanks for the help, your suggestion worked
