### ISSUE TITLE
Snyk still looks for our pom files

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#568]
Snyk still looks for dependencies in pom files and therefore fails. Snyk should be disabled or re-configured.

**Comment by persapiens** [comment]
Synk configured to look for build.gradle now.
Let's observe its behavior before closing this task.

**Comment by larsgrefer** [comment]
The Snyk check for https://github.com/joinfaces/joinfaces/pull/565 is green now 👍
