### ISSUE TITLE
Release 3.3.0-rc1

### ISSUE THREAD

**Issue by larsgrefer** [joinfaces/joinfaces#569]
I think we should release a milestone/RC/alpha/beta release in order to test the new gradle based publishing before finally releasing 3.3.0.

**Comment by persapiens** [comment]
When I run ` ./gradlew -DOSSRH_USER=${USER} -DOSSRH_PASS=${PASSWORD} publish`, I got the error:

```> Task :publishBomPublicationToMavenRepository FAILED
Could not transfer metadata org.joinfaces:joinfaces-dependencies:3.3.0-SNAPSHOT/maven-metadata.xml from/to remote (https://oss.sonatype.org/content/repositories/snapshots): Could not get resource 'org/joinfaces/joinfaces-dependencies/3.3.0-SNAPSHOT/maven-metadata.xml'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishBomPublicationToMavenRepository'.
> Failed to publish publication 'bom' to repository 'maven'
   > Failed to retrieve remote metadata org.joinfaces:joinfaces-dependencies:3.3.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.joinfaces:joinfaces-dependencies:3.3.0-SNAPSHOT/maven-metadata.xml from/to remote (https://oss.sonatype.org/content/repositories/snapshots): Could not get resource 'org/joinfaces/joinfaces-dependencies/3.3.0-SNAPSHOT/maven-metadata.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by larsgrefer** [comment]
The gradle build currently reads the credentials as environment variables (`System.getenv()`) becaus travis sets them this way https://travis-ci.org/joinfaces/joinfaces/jobs/450831543#L427-L428

Could you change the `.travis.yml` file in order to set them as
```
ORG_GRADLE_PROJECT_ossrhUser=foo
ORG_GRADLE_PROJECT_ossrhPass=bar
```

Setting them this way makes them available as `ossrhUser` and `ossrhPass` in the build.gradle file

For your local machine you can then add this to `~/.gradle/gradle.properties`:
```
ossrhUser=foo
ossrhUser=bar
```

See also: https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties

**Comment by persapiens** [comment]
I've set ~/.gradle/gradle.properties variables `ossrhUser=foo` and `ossrhPass=bar`, tried locally, but I got the same error.
I've set https://travis-ci.org/joinfaces/joinfaces/settings variables `ORG_GRADLE_PROJECT_ossrhUser=foo` and `ORG_GRADLE_PROJECT_ossrhPass=bar` too.

Of course, I've used real credentials.

**Comment by persapiens** [comment]
I rerun [build #1519](https://travis-ci.org/joinfaces/joinfaces/builds/450831542) again variables too. It seems  `openjdk11` works.

**Comment by persapiens** [comment]
I used to deploy with maven locally using `./mvnw release:clean release:prepare && ./mvwn release:perform`.

Could I do the same locally with `./gradlew publish`? Gradle changes SNAPSHOT to RELEASE version automatically?

**Comment by larsgrefer** [comment]
I've adjusted the `build.gradle` script to use the new gradle properties `ossrhUser` and `ossrhPass`

The build now fails with:
`Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/org/joinfaces/joinfaces-dependencies/3.3.0-SNAPSHOT/joinfaces-dependencies-3.3.0-20181106.224425-24.pom'. Received status code 401 from server: Unauthorized`

Could you re-check
- if the environment variables under https://travis-ci.org/joinfaces/joinfaces/settings contain the correct values (maybe you've made a typing error)
- if you local build works correctly with the properties set in `~/.gradle/gradle.properties`

**Comment by persapiens** [comment]
@larsgrefer I've just sent you email.
