### ISSUE TITLE
Feature request: restore a self-contained dependency starter

### ISSUE THREAD

**Issue by arcuri82** [joinfaces/joinfaces#575]
Hi,
  I have been working to upgrade an application from SpringBoot 1.5.4.RELEASE and Joinfaces 2.4.1 to latest 2.1.0.RELEASE and 3.2.3.
However, I had a lot of problems in such update. In the end, I managed to fix them, but the upgrade could had been smoother. 

Before, in  2.4.1, I could use Joinfaces by just adding:

```
 <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>jsf-spring-boot-starter</artifactId>
            <version>${joinfaces.version}</version>
 </dependency>
```

That was great, and simple ;) But, unfortunately, this does not seem to work anymore. In `pom.xml`, I had to explicitly add:

```
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <version>2.0</version>
        </dependency>
        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>el-api</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.web</groupId>
            <artifactId>el-impl</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet.jsp.jstl</groupId>
            <artifactId>javax.servlet.jsp.jstl-api</artifactId>
            <version>1.2.2</version>
        </dependency>
```

furthermore, I had to add:

```
    @Bean
    public ServletContextInitializer initializer() {
        return new ServletContextInitializer() {

            @Override
            public void onStartup(ServletContext servletContext) throws ServletException {
                servletContext.setInitParameter("com.sun.faces.expressionFactory",
                        "org.apache.el.ExpressionFactoryImpl");
            }
        };
    }
```

It would be great to have a "starter" dependency that just "works", like it was the case in 2.4.1, or at least have such info above in the documentation. My problem was that all examples there seem to use `joinfaces-parent`. Or is there one already existing but with a different name? (In that case, let me apologize in advance)

**Comment by larsgrefer** [comment]
Assuming you are using an embedded tomcat:

You have to exclude the `el-api` which is transitively pulled by `cdi-api`. Then you shouldn't need the other dependencies and the initializer

**Comment by arcuri82** [comment]
thanks for the very quick answer! Your sugesstiong does help a lot, although still need to add the JSTL library:

```
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <version>2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.el</groupId>
                    <artifactId>javax.el-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>      
        <dependency>
            <groupId>javax.servlet.jsp.jstl</groupId>
            <artifactId>javax.servlet.jsp.jstl-api</artifactId>
            <version>1.2.2</version>
        </dependency>
```

**Comment by larsgrefer** [comment]
Tomcat includes it's own EL implementation. If the el-api pulled in by cdi is also on the classpath it's non-deterministic which EL classes are loaded at runtime. (The tomcat el works by default, the el-api won't)

Could you provide a small example project which needs jstl to work? I'd like to investigate this a bit further

**Comment by arcuri82** [comment]
Hi. the project I am working on is open-source. That particular example can be found [here](https://github.com/arcuri82/testing_security_development_enterprise_systems/tree/master/intro/exercises/quiz-game/part-11), in the example exercise called "quiz-game-part-11"

**Comment by arcuri82** [comment]
thanks for the link

**Comment by larsgrefer** [comment]
We've reworked the starter dependencies with JoinFaces 4, so this should be fixed now.

If you still have problems, please open a new issue.
