### ISSUE TITLE
3.3.0 rc3 and maven repos.

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#590]
Just wondering if you have forgotten to upload the new rc3 version to maven? :)

**Comment by larsgrefer** [comment]
No, we haven't forgot it.
Some of our generated pom files didn't contain a `<name>` and `<description>` element, so maven central refused them.

I'm currently fixing this, and `3.3.0` based on Spring Boot 2.1.1 should follow later the day.

**Comment by bjorntj** [comment]
That explains it, thx.. :)
