### ISSUE TITLE
Rewrite Annotation Support

### ISSUE THREAD

**Issue by pmentz** [joinfaces/joinfaces#622]
Hi,
I want to refer to #392, where discussions about Rewrite functionality was going on. There it is told, that Rewrite annotation support as mentioned [in the Rewrite documentation](https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/configuration/annotations/index.asciidoc) would be working.

Unfortunately for me it was not working. When I was checking the [related source code](https://github.com/ocpsoft/rewrite/blob/master/annotations-impl/src/main/java/org/ocpsoft/rewrite/annotation/config/AnnotationConfigProvider.java), I could see that Rewrite in the used version is hard coded checking class files in _/WEB-INF/classes_ and alternatively _/WEB-INF/lib_ for supported annotations.

So in my opinion this feature is a missing, and I decided to add it via a PR.

It introduces an additional configuration option
`joinfaces.rewrite.scan-classpath`
which has to be set to `true` in order to enable scanning Spring beans in the class path for Rewrite annotations. This way the feature is backward compatible as it is disabled by default. As scanning all beans may take a lot of time during startup, this option should be used together with the 
`joinfaces.rewrite.base-packages`
configuration, to limit the packages to scan (another reason to not enable it by default). A warning is logged if the base-package configuration is missing.

**Comment by larsgrefer** [comment]
There is no need to open a separate issue if you're also opening a corresponding PR, so I'm closing this as a duplicate in favor of #623
