### ISSUE TITLE
Injectable PrimeFaces

### ISSUE THREAD

**Issue by melloware** [joinfaces/joinfaces#633]
PrimeFaces right now is a static utility similar to FacesContext you use it like PrimeFaces.current();

Submitting a PR to make it Autowirable to make injection and unit testing easier.

This will allow

```java
   @Autowired
   PrimeFaces primefaces;
```

**Comment by larsgrefer** [comment]
There is no need to open a separate issue if you're going to open a corresponding pull request.

So I'm closing this as a duplicate of #634

**Comment by melloware** [comment]
My apologies. I am a committer on Primefaces project and the policy is no PR is accepted without a corresponding issue ticket explaining the reason for the PR so it can be labeled with a version for release notes. 

In the future I will just submit a PR.
