### ISSUE TITLE
@PreDestruction or DisposableBean callbacks not working correctly on view scope

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#638]
I am using a view scoped bean defined like this 
`@Component
@Scope(scopeName = "view")
public class DeviceSearchBean implements DisposableBean {
...
}
`

When adding @PreDestroy or DisposableBean callback this will be called when the session expires and not when the view will be destroyed.

I am using joinfaces 3.2.3

**Comment by Tosken1337** [comment]
When i reload the page a new bean get's created, but the "old" one did not receive a destroy callback.

Shouldn't the view be destroyed when navigating away to a different page or does the jsf implementation (mojarra in this case) controls the destruction?

**Comment by larsgrefer** [comment]
Just reloading the page won't destroy the view. There are only two ways for a JSF view to get destroyed:

- When you actively navigate away from the current view using JSF navigation (action/outcome)
- When your session expires.

In your case (just reloading the page) the JSF implementation can't tell if you loaded the new view in the same window or in a new window, so it has to assume the old view might still be open.

**Comment by Tosken1337** [comment]
Okay thanks, my fault!
