### ISSUE TITLE
PrimeFaces.current() not being injected

### ISSUE THREAD

**Issue by melloware** [joinfaces/joinfaces#648]
I submitted a PR previosuly to make PrimeFaces.current() injectable.

I can see it in the latest trunk of source here: https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/PrimefacesAutoConfiguration.java#L45-L54

However I just decompiled JoinFaces 4.0.3 and I do not see this in the PrimefacesAutoConfiguration.  Am I missing something or is this somehow being compiled out?

**Comment by larsgrefer** [comment]
Your PR will be available in JoinFaces 4.1.x

**Comment by melloware** [comment]
Ahhh OK.
