### ISSUE TITLE
Support for Primefaces 7

### ISSUE THREAD

**Issue by OLibutzki** [joinfaces/joinfaces#649]
Primefaces 7 has been released yesterday. Is it possible just to "override" the dependency or do I have to wait for a new joinfaces release which has dependencies to Primefaces 7?

**Comment by melloware** [comment]
PR Submitted.  You may be able to override the current JoinFaces version with 7.0.  I know I do if for PF Elite releases and it works fine.  Just make sure to include PrimeFaces and PF Extensions as 7.0 in your pom.xml and you will get a warning that you are overriding an already declared version but that is OK.

**Comment by larsgrefer** [comment]
We haven't tested Primefaces 7 yet, but just overriding the dependency _should_ work.

**Comment by petterlarsen** [comment]
Do we have to exclude primefaces from the primefaces-spring-boot-starter in pom and then include a new dependency for Primefaces Elite? E.g Primfaces 7.0.17.

**Comment by melloware** [comment]
You can exclude it but if you just add 7.0.17 like you are doing that should override the 7.0 version in the Starter.   Just make sure you are using a JoinFaces version that is using PF 7 as the newest JoinFaces version already supports PF 8.0.

**Comment by larsgrefer** [comment]
@petterlarsen If you want to use another Primefaces Version than the one included by `primefaces-spring-boot-starter`, just don't use `primefaces-spring-boot-starter`, but only `jsf-spring-boot-starter` and declare the Primefaces dependencies yourself.

JoinFaces currently supports Primefaces 4-8 (with 8 beeing the default)
