### ISSUE TITLE
Update from 3.2.6 to 4.0.3 breaks security tags.

### ISSUE THREAD

**Issue by RaduFurnea** [joinfaces/joinfaces#656]
I updated from 3.2.6 to 4.0.3, the security tags are rendered in HTML instead of securing the app. 

```
<ui:composition xmlns:security="http://www.springframework.org/security/tags">
    <ui:define name="body">
        <security:authorize access="hasAnyAuthority('some_authority', 'some_other_authority')">
            <ui:include src="pages/documents/buttons.xhtml" />
        </security:authorize>
        <ui:include src="pages/documents/documents_list.xhtml" />
    </ui:define>
</ui:composition>
```

Instead of allowing users with those authorities, the tag is rendered in the HTML tree.

![image](https://user-images.githubusercontent.com/40205921/54921980-d4837700-4f0f-11e9-8e74-eb86331fce6a.png)

I'd appreciate any suggestions to what could have caused this.

**Comment by larsgrefer** [comment]
Can you provide a sample which reproduces the problem?

**Comment by gestern** [comment]
Confirmed the issue. Guys, when is it supposed to be fixed?

**Comment by larsgrefer** [comment]
@gestern Can you provide a sample project which reproduces this problem?

**Comment by gestern** [comment]
@larsgrefer Above the problem with an example is described completely, why the project? The problem is easily identifiable. Try the code above, it will work in 3.2.6, but 4.0.3 will not work.

**Comment by larsgrefer** [comment]
Do you have `org.joinfaces:joinfaces-security-taglib` on your classpath?

**Comment by larsgrefer** [comment]
@RaduFurnea @gestern Could you please try adding a dependency to `org.joinfaces:security-spring-boot-starter` to your projects?

**Comment by jeansossmeier** [comment]
@larsgrefer @RaduFurnea It looks like this version is no longer using the `http://www.springframework.org/security/tags` namespace, which now seems to be pointing to `https://joinfaces.org/security`.

In the snapshot documentation unfortunately this change is not being properly stated.  

Changing
 `<ui:composition xmlns:security="http://www.springframework.org/security/tags">` 
to
 `<ui:composition xmlns:security="https://joinfaces.org/security">`

 should work.

**Comment by larsgrefer** [comment]
JoinFaces 4.0.x still uses `http://www.springframework.org/security/tags`

JoinFaces 4.1.x will use `https://joinfaces.org/security`.

@jeansossmeier Thanks for bug-report regarding the documentation.

**Comment by berkson** [comment]
I sorry to comment in a already solved problem, but it's just to stay clear a problem in eclipse IDE validation.
When I use JoinFaces 4.1.x and Spring 2.2.X the application runs smoothly with the change mentioned above, but eclipse can't find the tag and keeps showing a warning marker in every xhtml that has the tag.
