### ISSUE TITLE
Demo not running on herokuapp

### ISSUE THREAD

**Issue by ullenboom** [joinfaces/joinfaces#657]
![image](https://user-images.githubusercontent.com/5071169/54983478-3e9e2980-4fad-11e9-931a-a29d246a9510.png)

**Comment by melloware** [comment]
@ullenboom you can see why here: https://github.com/joinfaces/joinfaces/issues/646

They have free sever and they run out of hours by the end of the month. Once April 1 hits it will be back up.

**Comment by melloware** [comment]
p.s I love your Avatar!
