### ISSUE TITLE
from java 8 to 11 | module not found: primefaces | module-info.java

### ISSUE THREAD

**Issue by StevenHachel** [joinfaces/joinfaces#675]
❓Question
Are there currently problems with the switch from java 8 to jigsaw? When building the project with Maven, I always get the line in the module-info.java file
`requires primefaces; `
with 

> ../java/module-info.java:[16,14] module not found: primefaces

 noted.

**Comment by larsgrefer** [comment]
I've never tried using JoinFaces or JSF on the modulepath. We currently only support the classpath.

**Comment by StevenHachel** [comment]
Okay, then it is not up to me. thanks for the information. :-) Great project. Keep it up. :-)
