### ISSUE TITLE
Extensionless mapping setting of MyFaces throws UnsupportedOperationException

### ISSUE THREAD

**Issue by nils-christian** [joinfaces/joinfaces#683]
Hi,

I tried to use the extensionless mapping setting of MyFaces with a Joinfaces 4.0.4 project, but the application immediately throws an error during startup:

```
java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getServletRegistrations(StandardContext.java:6571) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.myfaces.webapp.AbstractFacesInitializer.getFacesServletRegistration(AbstractFacesInitializer.java:834) ~[myfaces-impl-2.3.3.jar:2.3.3]
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initAutomaticExtensionlessMapping(AbstractFacesInitializer.java:820) ~[myfaces-impl-2.3.3.jar:2.3.3]
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:246) ~[myfaces-impl-2.3.3.jar:2.3.3]
```

I know that the error occurs in MyFaces, but according to Joinfaces documentation the parameter should work. Is there maybe something missing? 

I created a simple example project to demonstrate the issue at https://github.com/nils-christian/joinfaces-extensionless-mapping-issue. When you start the application, the error is thrown, but `http://localhost:8080/index.jsf` is available. The expected `http://localhost:8080/index` is not though.

Thank you and best regards,

  Nils

**Comment by larsgrefer** [comment]
Thanks for the detailed report 👍

I'll look into this

**Comment by larsgrefer** [comment]
MyFaces registers the `org.apache.myfaces.webapp.StartupServletContextListener` listener in its `web-fragment.xml` which works fine, when its deployed to an existing servlet container.

Spring Boot's embedded tomcat doesn't read `web-fragment.xml` files, therefore Joinfaces adds a `ServletContextInitializer` for this case which registers the listener instead:
https://github.com/joinfaces/joinfaces/blob/efe6aca0a810158027a1c18dff833201a11d33e7/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesAutoConfiguration.java#L51-L57

Apparently the listener registered via our `ServletContextInitializer` isn't allowed to call `javax.servlet.ServletContext#getServletRegistrations` while the same listener would be allowed to do so, if it would be registered via `web-fragment.xml`
