### ISSUE TITLE
 Extensionless mapping setting of MyFaces does not work

### ISSUE THREAD

**Issue by nils-christian** [joinfaces/joinfaces#687]
Hi,

I can confirm that the error from #683 does not occur any longer with Joinfaces 4.0.5, but it seems the mapping setting is still not working. 

Using my simple example from #683 and setting
`joinfaces.myfaces.automatic-extensionless-mapping=true`
I get an exception when I call `localhost:8080/index`:
`java.lang.ClassNotFoundException: javax.servlet.jsp.jstl.core.Config`
Strange enough, but this can easily be explained. Myfaces tries whether any available language (JSF or JSP) can handle the resource. JSF does not feel responsible, but _JspViewDeclarationLanguageStrategy_ always returns _true_. For JSP some classes are missing though (in this case: luckily).

It is therefore also necessary to set something like the following:
`joinfaces.jsf.facelets-view-mappings=*`
Now the _FaceletViewDeclarationLanguageStrategy_ feels responsible and handles the path. However, the resource loader is not able to find my _index.xhtml_ and throws an exception in _DefaultFaceletFactory.resolveURL_.

Is there still something missing? Maybe only in the configuration?

Thank you and best regards

  Nils

**Comment by larsgrefer** [comment]
I'm not sure if this a bug in MyFaces, but I found a workaround:

It works with `joinfaces.faces-servlet.url-mappings=*.xhtml`

This changes the return value of `org.apache.myfaces.shared.application.DefaultViewHandlerSupport#getFacesServletMapping` which in turn changes the behaviour of `org.apache.myfaces.shared.application.DefaultViewHandlerSupport#calculateViewId`.

**Comment by nils-christian** [comment]
Hi @larsgrefer,

Thank you. I can confirm that this works in a normal setup. In our case the prefixed web root (from #676) avoids that this works though. If you do not see this in the scope of Joinfaces (and I could very well understand this), you can close this ticket. Maybe I have to talk to the MyFaces developers instead. Something seems at least off in MyFaces.

Best regards

  Nils

**Comment by larsgrefer** [comment]
I have two ideas:

- Maybe the prefixed web root could work, if it also modifies the return values (the `getWebappPath()` of the returned `org.apache.catalina.WebResource`'s for example might have to be tweaked)

- Mabye you can solve both problems using [rewrite](https://www.ocpsoft.org/rewrite/).
(Mapping `{path}` to `a/{path}.xhtml` or `b/{path}.xhtml` depending on the Servlet Context could solve both problems)

**Comment by nils-christian** [comment]
Thank you very much for the hint, @larsgrefer. I agree that the solution with Rewrite is much easier. It solves both problems.
