### ISSUE TITLE
Field Injection for Rewrite services is not Applied

### ISSUE THREAD

**Issue by nils-christian** [joinfaces/joinfaces#692]
Hi,

We are using Joinfaces 4.0.5 with Rewrite. If we create a Spring managed Rewrite configuration which depends on field injection, the field injection is not actually applied.
```
@Component
@RewriteConfiguration
@ConditionalOnProperty( "prefix" )
public class PrefixRewriteConfiguration extends HttpConfigurationProvider {

	private String prefix;

	@Value( "${prefix}" )
	@Autowired
	public void setWebResourcePath( final String prefix) {
		this.prefix= prefix;
	}

	...

}
```

The reason is, that a _SpringBootServiceLocator_ is available and can find the component, but the injection is performed by the _SpringServiceEnricher_. This class depends on the current web application context, which seems to be not available in a Spring boot application. Instead a specific _SpringBootServiceEnricher_ is required, which could use the _ApplicationContextProvider_ of Joinfaces to perform the field injection in a correct way.

If you agree, I would provide a pull request for the issue.

Best regards,

  Nils

**Comment by melloware** [comment]
+1 from me.

**Comment by nils-christian** [comment]
I just realized that there already is a _SpringBootServiceEnricher_ on master (https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/SpringBootServiceEnricher.java). Maybe we can have a backport to 7.0.x instead?
