### ISSUE TITLE
javax Event breaks when injected

### ISSUE THREAD

**Issue by filipemb** [joinfaces/joinfaces#704]
Using springboot starter adminfaces-spring-boot-starter at: [https://github.com/adminfaces/admin-starter-springboot](https://github.com/adminfaces/admin-starter-springboot) 

When:

```java
@Named
@ViewScoped
public class FormMB implements Serializable {
	@Inject
	private Event<MyEvent> myEvent;
[...]
}
```
raises the exception:
```java
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type javax.enterprise.event.Event<MyEvent>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.inject.Inject()}
```

**Comment by larsgrefer** [comment]
`javax.enterprise.event.Event` seems to be a CDI feature. What exactly are you trying to achieve?

**Comment by larsgrefer** [comment]
You might be able to use Springs event support: https://docs.spring.io/spring-framework/docs/5.1.x/spring-framework-reference/core.html#context-functionality-events

**Comment by filipemb** [comment]
> `javax.enterprise.event.Event` seems to be a CDI feature. What exactly are you trying to achieve?

I'm trying to communicate with kafka to execute a process. I've implemented all with Spring Events and Listners (also with spring-kafka events and listners), but can't notify the user's online cos I could not get FacesContex inside a Spring @EventListner. So I'm trying to implement with javax.enterprise.event.Event.

**Comment by larsgrefer** [comment]
A `FacesContext` is only available during request processing in the corresponding java thread.

Therefore you can't access the `FacesContext` from background threads. For the same reason its not possible to send events to `@ViewScoped` (or `@SessionScoped`) beans.

**Comment by filipemb** [comment]
Ok. Since there is no support to CDI event. And `FacesContext `is not supposed to be used outside the request scope. The correct way to achieve this would be trough `@Inject @Push PushContext`. Is it supported?

**Comment by larsgrefer** [comment]
Unfortunately `PushContext` has Problems too, because it heavily depends on CDI: #690

**Comment by filipemb** [comment]
Digging deeper I found that JSR-330 ```@Inject``` annotation are included as an ```autowiredAnnotationTypes``` when present in classpath by ```AutowiredAnnotationBeanPostProcessor``` of Spring. 
Any suggestion to stop Spring from trying to Autowire ```@Inject``` annotations or, at least, to stop him from autowire ```javax.enterprise.event.Event```
Tried this: [Stackoverflow](https://stackoverflow.com/questions/7673856/spring-3-0-disable-inject-annotation-processing) but no success.

```java
@SuppressWarnings("unchecked")
    public AutowiredAnnotationBeanPostProcessor() {
        this.autowiredAnnotationTypes.add(Autowired.class);
        this.autowiredAnnotationTypes.add(Value.class);
        try {
            this.autowiredAnnotationTypes.add((Class<? extends Annotation>)
                    ClassUtils.forName("javax.inject.Inject", AutowiredAnnotationBeanPostProcessor.class.getClassLoader()));
            logger.info("JSR-330 'javax.inject.Inject' annotation found and supported for autowiring");
        }
        catch (ClassNotFoundException ex) {
            // JSR-330 API not available - simply skip.
        }
    }
```

**Comment by filipemb** [comment]
I'm closing this topic since the problem is actually in Spring `InitializingContext `configuration, and I'm posting a [Stackoverflow topic](https://stackoverflow.com/questions/57085681/override-default-autowiredannotationbeanpostprocessor-to-stop-jsr-330-support) about that. I'd suggest to include in JoinFaces readme the warning about CDI `Events `not supported as `PushContext`.

**Comment by filipemb** [comment]
I'm closing this topic since the problem is actually in Spring `InitializingContext `configuration, and I'm posting a [Stackoverflow topic](https://stackoverflow.com/questions/57085681/override-default-autowiredannotationbeanpostprocessor-to-stop-jsr-330-support) about that. I'd suggest to include in JoinFaces readme the warning about CDI `Events `not supported as `PushContext`.
