### ISSUE TITLE
UTF-8 Support in message.properties

### ISSUE THREAD

**Issue by StefanSchubert** [joinfaces/joinfaces#720]
Hi,

it's some years ago in the java 1.6 days when I did my last JSF application. For my new project I decided to stick with it instead of learning angularJS for several reasons. However I was really surprised to see that UTF-8 with property files is still an issue. It took me a couple of hours of research, since I was convinced that this is no longer a matter with java8, hm...

So my Problem is, that I stumbled over https://github.com/joinfaces/joinfaces/issues/486 in combination with UTF-8.

I also added the following to my application.properties

   spring.messages.basename=i18n/messages
   spring.messages.encoding=UTF-8
 
with no result, as my properties are being handled by JSF resouce bundling mechanisms and not via spring.

This was a bit disappointing to experience in 2019. I'm not sure if this issue can be solved with the help of joinfaces or with the help of mojarra or primefaces (which I'm using with joinfaces).

As i18n is mandatory for websites, I would recommend at least a paragraph in joinFaces Reference guide on how to configure i18n the right way for the use of utf-8 based messages, or if possible implement the glue code to use springs EL instead right into joinfaces (possible solution like this: https://jrebel.com/rebellabs/will-they-blend-how-to-use-spring-with-jsf-for-resource-bundling/ )

For my case I decided to use the workaround of maskerading the utf-8 characters with the help of my favourite IDE. So I see them correct in my editor, but the property file will be in ISO-8859-1 which is bad for other developers on github which IDE does not do this translation.

Kind regards
Stefan

**Comment by larsgrefer** [comment]
Thanks for the feedback 👍
