### ISSUE TITLE
Rewrite doesn't load @Join configuration

### ISSUE THREAD

**Issue by rherebia** [joinfaces/joinfaces#733]
I'm using JoinFaces 4.0.7 and I can't make rewrite annotation configuration work. I created [a simple project](https://github.com/joinfaces/joinfaces/files/3610517/joinfaces-rewrite-scan.tar.gz) and it's possible to access http://localhost:8080/index.xhtml, but not http://localhost:8080/welcome. 

The mapping is written in **br.com.rbh.view.WelcomeBean** with `@Join(path = "/welcome", to = "/index.xhtml")` and the property `joinfaces.rewrite.base-packages` is defined in application.yml with the package **br.com.rbh**. What is missing?

**Comment by larsgrefer** [comment]
Support for the annotations like `@Join` was added in #623 which will be part of JoinFaces 4.1.x.

For 4.0.x you can do something like this:

```java
@Bean
public HttpConfigurationProvider rewriteConfig() {
    return sc -> ConfigurationBuilder.begin()
               .addRule(Join.path("/welcome").to("/index.xhtml"));
}
```

**Comment by rherebia** [comment]
With your code I had the problem `The target type of this expression must be a functional interface`, so I adapted with:
```java
@Bean
public HttpConfigurationProvider rewriteConfig() {
	return new HttpConfigurationProvider() {
		
		@Override
		public int priority() {
			return 0;
		}
		
		@Override
		public Configuration getConfiguration(ServletContext context) {
			return ConfigurationBuilder.begin()
		               .addRule(Join.path("/welcome").to("/index.xhtml"));
		}
	};
}
```
And it worked! Thank you.

**Comment by rherebia** [comment]
With your code I had the problem `The target type of this expression must be a functional interface`, so I adapted with:
```java
@Bean
public HttpConfigurationProvider rewriteConfig() {
	return new HttpConfigurationProvider() {
		
		@Override
		public int priority() {
			return 0;
		}
		
		@Override
		public Configuration getConfiguration(ServletContext context) {
			return ConfigurationBuilder.begin()
		               .addRule(Join.path("/welcome").to("/index.xhtml"));
		}
	};
}
```
And it worked! Thank you.
