### ISSUE TITLE
War deployment documentation(correction)

### ISSUE THREAD

**Issue by ndopj** [joinfaces/joinfaces#735]
Given the example project you linked above, this here should work:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.thepracticaldeveloper</groupId>
    <artifactId>jboss-wildfly-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>jboss-wildfly-demo</name>
    <description>Simple Hola application deployable to Wildfly</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.2.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.joinfaces</groupId>
                <artifactId>joinfaces-dependencies</artifactId>
                <version>3.2.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>jsf-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.security</groupId>
                    <artifactId>spring-security-taglibs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.joinfaces</groupId>
            <artifactId>primefaces-spring-boot-starter</artifactId>
        </dependency>


        <!-- Dependencies which will be provided by WildFly -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.faces</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

```

_Originally posted by @larsgrefer in https://github.com/joinfaces/joinfaces/issues/475#issuecomment-389685545_

**Comment by ndopj** [comment]
Sorry for not editing initial message but for some reason i cannot edit it.
According to documentation, one should use mentioned pom.xml example to make .war file deploy-able on Full JavaEE servers.
Instead of this dependency:
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.faces</artifactId>
            <scope>provided</scope>
        </dependency>
use this one:
        <dependency>
            <groupId>javax.faces</groupId>
            <artifactId>javax.faces-api</artifactId>
            <version>your wildfly version jsf</version>
            <scope>provided</scope>
        </dependency>
Full JavaEE server will provide its own implementation of jsf, depending on version of JavaEE specification your server is using, therefore you only need to provide api.
Then add this dependency:
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.3</version>
        </dependency>
and application should be deploy-able on both, full JavaEE application servers(Wildfly, Glassfish) and servlet containers(Tomcat, Jetty). This was actually tested on Wildfly 17, Tomcat 9, Jetty 9.4, as i needed spring boot application using JSF 2.3 to be deploy-able on these servers.

**Comment by larsgrefer** [comment]
>and application should be deploy-able on both, full JavaEE application servers(Wildfly, Glassfish) and servlet containers(Tomcat, Jetty).

This won't be possible.
For full EE servers like wildfly, the application must not include a JSF implementation (Mojarra, MyFaces) and for servlet containers it must include a JSF implementation.
