### ISSUE TITLE
FacesConverter annotation and Java 11

### ISSUE THREAD

**Issue by Tosken1337** [joinfaces/joinfaces#757]
I am facing the issue, that converters registered with @FacesConverter are not get picked up when running the application with a jdk 11.

The app is build using jdk8 but when using an jdk 11 to start all my converters with @FacesConverter annotation will not picked up and thus an exception during runtime occurs because requested converters are not available.
Running with jdk 8 solves the issue.

Any ideas or is this a known issue with jdk 11?

I am using Version 3.2.6 of primefaces starter

Thanks

It seems that this is an issue of the reflections library used to scan the classpath for these annotations.
See https://github.com/ronmamo/reflections/pull/257

JsfClassFactory does not contain all classes

**Comment by larsgrefer** [comment]
You have to update to JoinFaces 4.x for full Java 11 support.

**Comment by Tosken1337** [comment]
okay, thank you
