### ISSUE TITLE
Spring Boot 2.2

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#759]
Not able to start a new project using Spring Boot 2.2.x aymore, since: "Could not find org.springframework.boot:spring-boot-dependencies:2.2.0.M6" (edit: guess this is because I did not include prerelease maven repos for Spring Boot... )

Any release for 2.2 in the near future?

**Comment by bjorntj** [comment]
Thx for RC 1... :)

**Comment by larsgrefer** [comment]
@bjorntj Did the RC1 work for you?

**Comment by bjorntj** [comment]
Yes, seems to be working fine.. :)

**Comment by srbala** [comment]
@bjorntj do you still have issue, if it is working for you, please close this issue

**Comment by bjorntj** [comment]
Still working... :)
