### ISSUE TITLE
Multiple FacesServlets for different context paths on the same port

### ISSUE THREAD

**Issue by elab** [joinfaces/joinfaces#771]
First of all, thank you very much for your impressive work!

I'm porting a typical multi-module JavaEE application (JSF / WLS) to Spring Boot (embedded Tomcat).

The original application is packaged as an EAR, which consists of multiple subapps. Each subapp is represented by a WAR and a lib-jar maven modules and is available under own context path when deployed, e.g. /appRoot/subapp1/... , /appRoot/subapp2/...
Java packages / maven dependencies reflect this namespace structure as well, i.e. there are common beans in appRoot package (available globally) and subapp-specific beans in appRoot.subapp1, appRoot.subapp2, etc.

How would you configure these modules to work with Spring Boot and JoinFaces?
I suppose, each subapp needs to explicitly define an own FacesServlet? But how to properly configure them? Which URL mappings to use? (JSF generally serves files using very strange paths, which do not exist in project structure, e.g. /javax.faces.resource/... or pictures as .xhtml: home.png.xhtml. So I'm not sure how it should be configured for different context paths.)

Essentially I think I'd like to achieve the same as here https://github.com/stojsavljevic/multi-ctx/tree/master/multi-ctx-app-servlets (Article: https://ccbill.com/blog/spring-boot-and-context-handling, see section "2. ServletRegistrationBean" there) but with FacesServlets instead of DispatcherServlets.

Thank you for your thoughts.

**Comment by melloware** [comment]
Me personally is I would make each individual WAR its own JoinFaces app.  Spring Boot is meant to serve one context on one port for microcontainers.  Not multiple WARS inside the same Spring Boot instance.

**Comment by larsgrefer** [comment]
@elab When reading the article you've mentioned, you have to distinguish between two different types of contexts:

- Spring Application Context
- Servlet Context

In your ear application, you get one Servlet Context for each war file. Each Serlvet Context then gets it's own FacesServlet, it's own classpath and it's own set of resources.
Each Servlet Context can have one or more Spring Application Contexts.

The article you've mentioned is about a setup with multiple Spring Application Contexts in one Servlet Context.

A default Spring Boot application (and therefore a default JoinFaces application) has one Spring Application Context and one Servlet Context. Spring Boot can either re-use and exising Servlet Context (when deployed as war file to an existing servlet container) or start it's own Servlet Context by using an embedded Servlet Container (Tomcat, Jetty or Undertow).

I'm not sure if it's possible to have multiple Servlet Contexts in one Spring Boot application.

**Comment by elab** [comment]
I could create an additional FacesServlet as follows (in a child module "admin"), analogous to `org.joinfaces.autoconfigure.javaxfaces.FacesServletAutoConfiguration.facesServletRegistrationBean(FacesServletProperties)`:

```
@SpringBootConfiguration
@ComponentScan
@EnableWebMvc
public class Config {

    @Bean
    public ServletRegistrationBean<FacesServlet> adminGui() {
        ServletRegistrationBean<FacesServlet> servletRegistrationBean = new ServletRegistrationBean<FacesServlet>(new FacesServlet(), "/admin/*") {

            @Override
            protected ServletRegistration.Dynamic addRegistration(String description, ServletContext servletContext) {
                ServletRegistration.Dynamic servletRegistration = super.addRegistration(description, servletContext);
                if (servletRegistration != null) {
                    servletContext.setAttribute("org.apache.myfaces.DYNAMICALLY_ADDED_FACES_SERVLET", true);
                    servletContext.setAttribute("com.sun.faces.facesInitializerMappingsAdded", true);
                }
                return servletRegistration;
            }
        };
        servletRegistrationBean.setName("admin");
        servletRegistrationBean.setLoadOnStartup(1);
        servletRegistrationBean.setOrder(0);

        return servletRegistrationBean;
    }
}
```
With debugging enabled, I see in the log that the new FacesServlet "admin" gets indeed registered:
```
2019-12-03 14:41:48,304   [21] DEBUG o.s.b.w.s.ServletContextInitializerBeans:logMappings           235 - 
Mapping servlets: admin urls=[/admin/*], FacesServlet urls=[/faces/*, *.jsf, *.faces, *.xhtml], dispatcherServlet urls=[/], webServlet urls=[/h2-console/*]
```
But when I'm trying to access the page /admin/index.xhtml, the root /index.xhtml is instead rendered in browser.

**Comment by elab** [comment]
The types and relationships between contexts are indeed not completely clear to me. For example, in the log above we see 4 servlets. To which contexts are they related?

**Comment by larsgrefer** [comment]
@elab With your adminGui servlet, you now have 2 FacesServlets in the same Spring Application Context and therefore in the same Servlet Context. (In fact all 4 servlets come from the same Spring Application Context and are installed in the same Servlet Context)

It shouldn't be necessary to have multiple FacesServlets in the same Servlet Context.
You only need multiple FacesServlets when you have multiple Servlet Contexts (one FacesServlet per Servlet Context).

**Comment by elab** [comment]
@larsgrefer The aim was to have a distinct context (Servlet Context? Application Context?) for the new FacesServlet. I just didn't find a way to do that, like it's done [here](https://github.com/stojsavljevic/multi-ctx/blob/master/multi-ctx-app-servlets/src/main/java/com/alex/demo/ctx/parent/ParentCtxConfig.java#L28) for DispatcherServlet as there is no FacesServlet.setApplicationContext or FacesServlet.setServletContext method.

If you mean, multiple Faces Servlets aren't necessary for my purpose, it would also be perfectly fine! As long as it could be possible to serve content from subapps using their current context paths.
Perhaps I should try to transform all the web modules to web-fragment JAR modules (all web resources moved to `META-INF/resources` inside JAR)? Or some other way?

**Comment by elab** [comment]
The problem is that the original EAR application has JSF/CDI beans with the same simple names in its WAR subapplications. If that names are used in EL expressions inside JSF facelets (.xhtml pages), then how to decide which bean to use (bean names resolution) without having distinct "bean containers" per subapplication (i.e. per context path) in a single Spring Boot app?

(There is an (implied) 1-to-1 mapping between Java packages which contain beans and global web context paths, e.g.: package `subapp1.*` <-> context path `/subapp1/*`)

Perhaps an own implementation of [`SpringBeanFacesELResolver`](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/jsf/el/SpringBeanFacesELResolver.java) would suffice? Such an implementation should first look up beans in a current per-context-path context (a Spring `WebApplicationContext`) and then if not found in the parent-context-path context.

**Comment by larsgrefer** [comment]
If you want to keep your bean names, you definitely need different Spring Contexts.

You could try building one Spring Boot application with a context hierarchy:
- parentContext
  - subContext1
  - subContext2

The parent context could contain the embedded tomcat, the Faces Servlet and the common beans from your old appRoot package. The subContexts could then reflect your old sub-apps.
An own SpringBeanFacesELResolver could then decide depending on the viewId in which context to look.

**Comment by elab** [comment]
How to configure an own SpringBeanFacesELResolver instead of the [JoinFaces default one](https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/resources/META-INF/faces-config.xml#L16) without `faces-config.xml`?

**Comment by larsgrefer** [comment]
You'll need a faces-config.xml to do that.
