### ISSUE TITLE
error: cannot access Qualifier

### ISSUE THREAD

**Issue by bjorntj** [joinfaces/joinfaces#810]
Hi.

When I use version 4.3.0 in my gradle build and tries to comile it with Java 8, I get the following error:

`error: cannot access Qualifier
  class file for javax.inject.Qualifier not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for javax.inject.Qualifier not found`

Compiling it with Java 11 works fine. Going back to Joinfaces 4.1.5, makes my code compile fine using Java 8.

Is this a known problem or is it something at my end or? (searched my whole project for Qualifier but as far as I can see, my code does not use this...)

**Comment by larsgrefer** [comment]
Can you provide an project which reproduces this?

**Comment by bjorntj** [comment]
I'll see what I can do..

**Comment by bjorntj** [comment]
Did some more research (as it was not quite that easy to create a little test project...) and found out that this dependency was missing: javax.enterprise:cdi-api
Not sure what happend between Joinfaces version 4.1.5 and 4.3.0 for this to pop up?
