### ISSUE TITLE
Move 'richfaces' to the only live supported fork version 4.6.12.avg

### ISSUE THREAD

**Issue by hazendaz** [joinfaces/joinfaces#811]
While richfaces is long obsolete, there is a fork that is keeping it alive and fixing vulnerabilities with it.  It would be nice to stop having to exclude the non supported jboss original.  We have been successfully using the fork up to jdk 14 without issue since late last year.

The fork repo is [here](https://github.com/albfernandez/richfaces)

All the GAVs can be found [here](https://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22com.github.albfernandez.richfaces%22)

**Comment by melloware** [comment]
That is a good suggestion

**Comment by larsgrefer** [comment]
I'd prefer adding a second starter for this

**Comment by hazendaz** [comment]
Second starter seems like unnecessary overhead.  Jboss dropped support about 4 years ago with Richfaces.  The replacement we have used without any modification needs, in fact its a direct fork.  The only problem with joinfaces is that we have to use lots of exclusions.  If anyone was using richfaces, it should be completely drop in place.  Nothing is being done with richfaces other than fixing vulnerabilities and keeping it up-to-date with latest build requirements.  I'm one of the developers that have helped with that as migrating elsewhere just wasn't directly in the cards.

**Comment by larsgrefer** [comment]
> The only problem with joinfaces is that we have to use lots of exclusions.

What exclusions do you have to use?

**Comment by hazendaz** [comment]
The original richfaces GAV.  The groupId had to change.

**Comment by hazendaz** [comment]
That said, I can undertand the second starter for backwards support.  However, it still feels a bit of overwork given jboss isn't ever going to release another version.

**Comment by hazendaz** [comment]
I should add the last released richfaces jboss version is vulnerable thus why it was forked to start with.  That probably should be considered.  Maybe new started by mark old one as deprecated ?

**Comment by melloware** [comment]
agreed the jboss version is dead and has security flaws that have been patched.

**Comment by larsgrefer** [comment]
Integrating the richfaces fork with JoinFaces should be as simple as:

```gradle
dependencies {
    implementation "org.joinfaces:jsf-spring-boot-starter"
    implementation "com.github.albfernandez.richfaces:richfaces:4.6.13.ayg"
}
```

**Comment by hazendaz** [comment]
@larsgrefer OK - I looked deeper, yes another starter wouldn't be that bad at all.  For some reason I was thinking there was more involved.  That looks pretty simple.  Would you like me to raise a PR for this?

**Comment by melloware** [comment]
please raise a PR!

**Comment by arjantijms** [comment]
Just wondering, has that PR ever been raised?

**Comment by melloware** [comment]
@arjantijms I raised a PR and it was rejected. See: https://github.com/joinfaces/joinfaces/pull/812

**Comment by melloware** [comment]
Oh no i see a new starter was requested.  No no PR was ever submitted.

**Comment by hazendaz** [comment]
I had written the code but never submitted as I had issues getting this to even build at the time.  Trying again now...
