### ISSUE TITLE
HI,When I use primefaces-spring-boot-starter, I need to restart every time I modify xhtml.

### ISSUE THREAD

**Issue by eric-5512** [joinfaces/joinfaces#816]
When I use primefaces-spring-boot-starter, I need to restart every time I modify xhtml.

My directory structure:

![image](https://user-images.githubusercontent.com/56282991/84217471-d3336f80-aafe-11ea-842b-bd1a6fc67541.png)

**Comment by melloware** [comment]
This is a duplicate of: https://github.com/joinfaces/joinfaces/issues/621

**Comment by eric-5512** [comment]
OK thank
