### ISSUE TITLE
Question: how to use OmniFaces NoAutoGeneratedIdViewHandler through JoinFaces?

### ISSUE THREAD

**Issue by nicerloop** [joinfaces/joinfaces#819]
Hi,

I am a newcomer to Joinfaces and JSF with Spring, but not with Spring Boot.
How would I register/use OmniFaces NoAutoGeneratedIdViewHandler through JoinFaces?

Thanks?

https://showcase.omnifaces.org/viewhandlers/NoAutoGeneratedIdViewHandler

**Comment by melloware** [comment]
it is easy.  Look for this file in your project.
`\src\main\resources\META-INF\faces-config.xml`

If not found create one, if it was found simply edit it and add this...
```xml
<?xml version="1.0" encoding="UTF-8"?>
<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_3.xsd" version="2.3"
>
    <application>
        <view-handler>org.omnifaces.viewhandler.NoAutoGeneratedIdViewHandler</view-handler>
    </application>

    <!-- make sure this is loaded after OmniFaces-->
    <ordering>
        <after>
            <name>omnifaces</name>
        </after>
    </ordering>
</faces-config>
```

**Comment by nicerloop** [comment]
I created a new Maven project according to https://docs.joinfaces.org/current/reference/#_maven
I added omnifaces3-spring-boot-starter, a faces-config.xml as you described, and a minimum @SpringBootApplication
The application errors on start: Exceeded maximum number of attempts to sort the faces-config documents
I tried without the explicit ordering part, no NoAutoGeneratedIdViewHandler is created (my breakpoint is never reached)

What am I doing wrong?

**Comment by melloware** [comment]
The way I got started was to use this app: https://github.com/joinfaces/joinfaces-maven-jar-example

Run that app and it walks you through setting up the project by letting you pick "PrimeFaces, OmniFaces, MyFaces" etc and then configures a proper Maven pom.xml for you.

**Comment by nicerloop** [comment]
Mojarra cannot resolve the ordering directives, whereas MyFaces can. It works with MyFaces. Thanks.

**Comment by melloware** [comment]
HA yeah when using Joinfaces i ONLY use MyFaces because it is superior to Mojarra in every way.  Bug fixing, performance, you name it.

**Comment by nicerloop** [comment]
I was starting with our current product catalog (spring + mojarra), just upgrading and throwing in JoinFaces.
In fact , Mojarra manages to order the different faces-config.xml correctly one I gave a name to mine.
