### ISSUE TITLE
joinfaces-maven-war-example joinfaces-maven-plugin Plugin could not be resolved

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#833]
tried to use joinfaces-maven-war-example as is in the Spring Tools Suite 4.

File joinfaces-maven-plugin-4.3.4.jar exists under ...\.m2\repository\org\joinfaces\joinfaces-maven-plugin\4.3.4\

Am i missing some more set up ? Thanks for help.

Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present. Additional information: Plugin org.joinfaces:joinfaces-
 maven-plugin:4.3.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.joinfaces:joinfaces-maven-plugin:jar:4.3.4

Plugin execution not covered by lifecycle configuration: org.joinfaces:joinfaces-maven-plugin:4.3.4:classpath-scan (execution: default, phase: process-
 classes)

**Comment by melloware** [comment]
another one?
