### ISSUE TITLE
How to override PF jar file

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#835]
Joinfaces is using PF v8.0. 
I have PF v8.0.4 jar file. 
How should I override Joinfaces PF v8.0 jar file with my PF jar v8.0.4 ? 
Thanks.

**Comment by melloware** [comment]
Just add PrimeFaces to your pom.xml and it will override the version in the JoinFaces Starter as Maven will use you version instead.
```xml
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>8.0.4</version>
		</dependency>
```

**Comment by vitsin** [comment]
Once I add above into pom.xml: Missing artifact org.primefaces:primefaces:jar:8.0.4
Do I also need to add my PF v8.0.4 jar file into Java Build Path ?

**Comment by melloware** [comment]
You need to add it to your local /.m2 maven repository for maven to find it.

**Comment by vitsin** [comment]
thanks, working perfect now!
GET http://localhost:8080/javax.faces.resource/components.css.xhtml?ln=primefaces&v=8.0.4

**Comment by melloware** [comment]
No problem.
