### ISSUE TITLE
primefaces-spring-boot-starter mixed with Spring Web MVC

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#836]
Below is more a question rather than issue.

If I use joinfaces primefaces-spring-boot-starter in mix with Spring Web MVC spring-boot-starter-web, where in the project should I place the XHTML files and what URL should I use than ?

I've tried src/main/resources/web2/landing.xhtml - no luck, going to localhost:8080/bla/landing.xhtml  returns error
I've tried src/main/webapp/WEB-INF/views/landing.xhtml - no luck, going to localhost:8080/bla/landing.xhtml  returns error

application.properties
JSF setup
```
joinfaces.faces-servlet.async-supported=true
joinfaces.faces-servlet.enabled=true
joinfaces.faces-servlet.load-on-startup=1
joinfaces.faces-servlet.name=FacesServlet
joinfaces.faces-servlet.order=0
joinfaces.faces-servlet.url-mappings=/faces/*,*.jsf,*.faces,*.xhtml
joinfaces.jsf.config-files=faces-config.xml
joinfaces.jsf.default-suffix=*.xhtml
joinfaces.jsf.datetimeconverter-default-timezone-is-system-timezone=true
joinfaces.jsf.facelets-refresh-period=1
joinfaces.jsf.facelets-skip-comments=true
joinfaces.jsf.interpret-empty-string-submitted-values-as-null=true
joinfaces.jsf.facelets-libraries=/tags/my.taglib.xml
```

Spring MVC
```
spring.mvc.log-resolved-exception=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.view.prefix=/web2/
spring.mvc.view.suffix=.xhtml
spring.mvc.servlet.load-on-startup=1
spring.mvc.servlet.path=/bla/
spring.mvc.static-path-pattern=/static/**
```

**Comment by melloware** [comment]
You don't want to mix them. You either use JSF or Spring MVC but not both.  I would remove all Spring MVC.

**Comment by vitsin** [comment]
ok, fine, say I remove Spring MVC. Than how can be achieved navigations between various application's pages? 
Landing page have a login which will lead to welcome page which will have links to other pages, something like that ?

**Comment by larsgrefer** [comment]
Using both JSF and Spring MVC should be no problem. One could have a JSF based user interface and a Spring MVC based REST-interface in the same application.

The JSF views must be located in the servlet webroot. For jar-based application this is `classpath:/META-INF/resources/` (so `src/main/resources/META-INF/resources` when working with Maven or Gradle). For war-based application the web-root is the root of the war file (so `src/main/webapp` for Maven/Gradle)

You should also have a look at these example projects:

https://github.com/joinfaces/joinfaces-gradle-jar-example
https://github.com/joinfaces/joinfaces-gradle-war-example

**Comment by melloware** [comment]
Sorry I misunderstood i was under the impression @vitsin wanted to mix SpringMVC UI pages with JSF UI pages and how to navigate between them.  Wasn't thinking REST Services only.

**Comment by vitsin** [comment]
thank you both guys! 
Actually both answers pretty much clarifying the picture of web-GUI and REST API.

On the other hand, for the JSF views, if I go with Mojarra implementation, what system should/could be used for JSF navigation between views?

**Comment by melloware** [comment]
1. Definitely go with Myfaces.  I have been using JSF for 10 years and MyFaces has less bugs, is 25% faster rendering and is just way more mature that Mojarra.

2. I just use Outcomes to navigate to pages directly.
```xml
<p:menuitem id="mni_business_line" value="Business Line" icon="fa fa-fw fa-building" outcome="/view/dashboard" />
```

Which navigates to my XHTML JSF page in my app found here:
```
\src\main\resources\META-INF\resources\view\dashboard.xhtml
```

**Comment by vitsin** [comment]
nice!
how can I replace default mojarra-spring-boot-starter with myfaces-spring-boot-starter if I still use primefaces-spring-boot-starter ?

**Comment by melloware** [comment]
I am a huge fan for performance in JoinFaces...
Undertow -> Instead of Tomcat/jetty
Myfaces -> Instead of Mojarra

This has the lowest memory footprint and fastest performance of all the combinations.

My pom.xml looks like this...
```xml
<!-- Spring Boot and Cloud -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-oauth2</artifactId>
		</dependency>
		<!-- JoinFaces -->
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>primefaces-spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.joinfaces</groupId>
					<artifactId>tomcat-spring-boot-starter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.joinfaces</groupId>
					<artifactId>mojarra-spring-boot-starter</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>omnifaces3-spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.joinfaces</groupId>
					<artifactId>tomcat-spring-boot-starter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.joinfaces</groupId>
					<artifactId>mojarra-spring-boot-starter</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>undertow-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>myfaces-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>rewrite-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>weld-spring-boot-starter</artifactId>
		</dependency>
		<!-- PrimeFaces Library and Theme -->
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>${primefaces.version}</version>
		</dependency>
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>babylon-theme</artifactId>
		</dependency>
```

**Comment by vitsin** [comment]
Why would we need Undertow definition twice than ? One for web-GUI and another one for REST API?

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
		</dependency>
```
```
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>undertow-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
```

**Comment by vitsin** [comment]
Kinda not sure about Undertow: what about session timeout, tracking mode, cookies age, etc ? 
All I see under joinfaces is joinfaces.undertow.class-path-resource param.
Tomcat on the other hand has it all.

**Comment by melloware** [comment]
One is the JoinFaces starter and the other is the Spring Boot Starter.  You may not need the Spring Boot one if JoinFaces brings it in automatically.

Undertow supports it all under the "server" config like this...
```yaml
server:
  port: ${PORT:8080}
  use-forward-headers: true
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
  servlet:
    context-path: /
    session:
      timeout: 30m
      tracking-modes:
      - cookie
      cookie:
        http-only: true
        secure: false
```

**Comment by vitsin** [comment]
so if I don't need spring-boot-starter-undertow, than Undertow setup you showed still will work ?

**Comment by melloware** [comment]
it should work fine and enables HTTP2 by default also which is a nice bonus of Undertow.

**Comment by vitsin** [comment]
thanks, I'll give it a try now.

**Comment by larsgrefer** [comment]
> how can I replace default mojarra-spring-boot-starter with myfaces-spring-boot-starter if I still use primefaces-spring-boot-starter ?

This is described here: https://docs.joinfaces.org/4.3.x/reference/#_not_using_tomcat_or_mojarra

**Comment by vitsin** [comment]
1. if I add some Spring Security login page
```
formLogin().loginPage("/login.xhtml")
```
is it possible to avoid XHTML suffix usage using Joinfaces setup?
I've tried to set joinfaces.jsf.default-suffix=*.xhtml, but no luck.

2.if I use war deployment, create src/main/webapp/WEB-INF/resources/login.xhtml
and set joinfaces.undertow.class-path-resource=/webapp/WEB-INF/resources, than login.xhtml should be my app's login page ?

Am I understanding above correctly, pls point me to my error. Thanks.

**Comment by larsgrefer** [comment]
>1.
When using a JSF view as spring security form login, you have to make sure, that the form on the login page generates a POST request which can be processed by `org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter`

If you are using MyFaces, you could try its extensionless mapping feature: `joinfaces.myfaces.automatic-extensionless-mapping`
You could also use Rewrite (https://docs.joinfaces.org/4.3.x/reference/#_rewrite) to internally forward requests from `/foo` to `/foo.xhtml`

> 2.if I use war deployment, create `src/main/webapp/WEB-INF/resources/login.xhtml`
and set `joinfaces.undertow.class-path-resource=/webapp/WEB-INF/resources`, than login.xhtml should be my app's login page ?

No

`joinfaces.undertow.class-path-resource` refers to a location in the applications classpath and `src/main/webapp` is not in the classpath. This property is mainly made for jar-based applications, which don't have a servlet web root. If you are using war deployment, you have a dedicated web root (namely `src/main/webapp`) so you don't have to put you views on the classpath.

If you want your `login.xhtml` view to be accessible under `localhost:8080/login.xhtml` just put it under `src/main/webapp/login.xhtml` (for war-based applications). For jar-based applications you would have to put it under `src/main/resources/META-INF/resources/login.xhtml`

If you set `joinfaces.undertow.class-path-resource=/webapp/WEB-INF/resources` the resulting path would be `src/main/resources/webapp/WEB-INF/resources/login.xhtml`

**Comment by vitsin** [comment]
Greatly appreciate your help!

**Comment by melloware** [comment]
Is this ticket safe to close now that you have your local project working?
