### ISSUE TITLE
UT010021: Path faces-config.xml must start with a /

### ISSUE THREAD

**Issue by vitsin** [joinfaces/joinfaces#838]
JoinFaces: 4.3.4
+ Undertow/MyFaces/Rewrite/Weld/Omnifaces3 using primefaces-spring-boot-starter starter.

File faces-config.xml located under /myProj/src/main/resources/META-INF/faces-config.xml

```
ERROR org.apache.myfaces.config.FacesConfigurator %PARSER_ERROR[x] [o.a.m.c.FacesConfigurator:312] - Could not read resource faces-config.xml
java.net.MalformedURLException: UT010021: Path faces-config.xml must start with a /
	at io.undertow.servlet.spec.ServletContextImpl.getResource(ServletContextImpl.java:293)
```

**Comment by melloware** [comment]
My last version using this combination was JoinFaces 4.0.3 and this was not an issue so either is a new MyFaces validation or a new Undertow issue possibly?

**Comment by melloware** [comment]
I was able to get my project working fine on. Spring Boot 2.3.5 with Joinfaces 4.3.4

```xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.5.RELEASE</version>
        <relativePath />
        <!-- lookup parent from repository -->
    </parent>
```

 <joinfaces.version>4.3.4</joinfaces.version>

**Comment by vitsin** [comment]
All working fine once I've removed:
```
joinfaces.jsf.config-files=faces-config.xml
```
Default faces-config.xml should be placed under /myProj/src/main/resources/META-INF/

**Comment by melloware** [comment]
Nice. Safe to close this ticket.
