### ISSUE TITLE
Exclude resources from using the default servlet suffix '*.jsf'

### ISSUE THREAD

**Issue by stefan-dan** [joinfaces/joinfaces#840]
Hi there!

By default joinfaces add '.jsf' suffix for javax.faces.resource. 
Can you tell me please how to exclude it?

Also in your examples, if you inspect an image from 'starter.jsf' in Chrome, you can see that resources get the '.jsf' suffix.
Example: `/javax.faces.resource/images/tomcat.png.jsf?pfdrid_c=true`

**Comment by FMusic** [comment]
this also doesn't work for me
