### ISSUE TITLE
primface upload p:fileUpload listener not work

### ISSUE THREAD

**Issue by eric-5512** [joinfaces/joinfaces#842]
config

joinfaces:
  jsf:
    PROJECT_STAGE: Development
  primefaces:
    theme: california-alive
    font-awesome: true
    uploader:  native
  omnifaces:
    faces-views-enabled: true

I need ajax to submit images.

**Comment by melloware** [comment]
What doesn't work. What error are you getting?

**Comment by eric-5512** [comment]
HI @melloware 

```
 <p:fileUpload id="orderImageId" value="#{createNewOrderView.file}" listener="#{createNewOrderView.uploadHandler}"
                                                  mode="simple" skinSimple="true"    allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
                                                     sizeLimit="1048576"   auto="true" fileLimit="1"  fileLimitMessage="只允许上传1个文件"
                                                  label="选择文件"  uploadLabel="上传" cancelLabel="取消" />
```

 public void uploadHandler(FileUploadEvent event) {
        file = event.getFile();
  }

According to the uploadHandler method of the listener, it has never been called and there is no error message.

**Comment by eric-5512** [comment]
我现在能通过以下标签获得上传文件.

<p:commandButton ajax="false" value="upload" />

**Comment by melloware** [comment]
You are mixed up.

In Simple mode you use `value=""` and not `listener=""`.  See this example: https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml

In Advanced mode you use `listener=""` and NOT `value=""`. See this example:
https://www.primefaces.org/showcase/ui/file/upload/single.xhtml

**Comment by eric-5512** [comment]
HI @melloware 
Thank you!
