### ISSUE TITLE
Support for Openfaces

### ISSUE THREAD

**Issue by per-steinar** [joinfaces/joinfaces#847]
Does Joinfaces have any support for Openfaces? I have upgraded an older application to springboot and Joinfaces. It is mainly based on Richfaces and standard JSF-components, but uses the treeTable feature from Openfaces. Or are there any other JSF-framework that is supported by Joinfaces and which has this feature?

As I can see, the Openfaces project is pretty abandoned.

**Comment by melloware** [comment]
PrimeFaces has a TreeTable and is supported by JoinFaces.

See: https://www.primefaces.org/showcase/ui/data/treetable/basic.xhtml

**Comment by per-steinar** [comment]
Thanks. I will look into PrimeFaces.
