### ISSUE TITLE
Support for MyFaces 2.3-next

### ISSUE THREAD

**Issue by tandraschko** [joinfaces/joinfaces#865]
Hey!

i'm not a user of joinfaces but i'm a maintainer of MyFaces and i would like to suggest you, to try 2.3-next instead of 2.3.
2.3-next is a complete cleanup of 2.3 but with removed @ManagedBean support, they are bridged to CDI beans actually, which shouldnt hurt as you rely on Spring beans anyway.

Here is my blog about it:
http://tandraschko.blogspot.com/2019/03/way-to-myfaces-30.html

less size, improved performance.

it would at least great if someone could give it a try. Currently its only used by Quarkus users probably.

**Comment by melloware** [comment]
@tandraschko  From reading your blog post comments does this mean that OmniFaces cannot be used with NEXT?   Because my JoinFaces stack is UnderTow + MyFaces + OmniFaces + PrimeFaces.

**Comment by tandraschko** [comment]
actually omnifaces should work, why do you think it shouldnt work?

**Comment by larsgrefer** [comment]
@tandraschko What would be the correct maven coordinates for 2.3-next?

**Comment by tandraschko** [comment]
https://search.maven.org/artifact/org.apache.myfaces.core/myfaces-api/2.3-next-M4/jar
https://search.maven.org/artifact/org.apache.myfaces.core/myfaces-impl/2.3-next-M4/jar

M5 will follow soon

**Comment by larsgrefer** [comment]
@tandraschko While working on #1163 I noticed two incompatibilities between 2.3 and 2.3-next:

- The Interface `org.apache.myfaces.shared.util.serial.SerialFactory` doesn't exist anymore
- The class `org.apache.myfaces.ee.MyFacesContainerInitializer` is deprecated an has been moved to `org.apache.myfaces.webapp.MyFacesContainerInitializer`

Apart from this, 2.3-next seems to run fine with Joinfaces 4.6.0-m1 on Spring Boot 2.6.0-m1

**Comment by larsgrefer** [comment]
MyFaces 2.3-next will be supported by JoinFaces 4.6.x
see #1163
