### ISSUE TITLE
Joinfaces support JSF Primefaces 10

### ISSUE THREAD

**Issue by stefan-dan** [joinfaces/joinfaces#866]
When **Joinfaces** is planning to support **JSF Primefaces 10**?

**Comment by melloware** [comment]
There are some new WebInf Context params that need to be added to joinfaces for PF10 like `TOUCHABLE`, `FLEX`, `MARK_INPUT_AS_INVALID_ON_ERROR_MSG`

**Comment by persapiens** [comment]
Hi @stefan-dan and @melloware,

You could PR PrimeFaces 10 support. Do the following tasks:
- change primefaces and primefaces-extensions versions at [build.gradle](https://github.com/joinfaces/joinfaces/blob/master/build.gradle). We bundle primefaces and primefaces-extensions together.
- create Primefaces10_0Properties.java with new WebInf Context Params. See [Primefaces8_0Properties.java](https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/Primefaces8_0Properties.java) as example.
- configure Primefaces10_0Properties at [PrimefacesAutoConfiguration](https://github.com/joinfaces/joinfaces/blob/master/joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/PrimefacesAutoConfiguration.java). Use Primefaces8_0Properties auto configuration as example.

**Comment by melloware** [comment]
Yep I did the 8.0 PR I can do the 10.0 PR.
