### ISSUE TITLE
Dialog now showing

### ISSUE THREAD

**Issue by yashanet** [joinfaces/joinfaces#869]
Actually Im working with in a web project, Im Using primefaces with joinfaces.
The instruction primefaces.current().dialog().opendynamic not working i think that is beacause in faces-config.xml file is not configured:
<application> <action-listener> org.primefaces.application.DialogActionListener </action-listener> <navigation-handler> org.primefaces.application.DialogNavigationHandler </navigation-handler> <view-handler> org.primefaces.application.DialogViewHandler </view-handler> </application>

Could you help me to think in a solution for this ???

**Comment by melloware** [comment]
Yes those go in your faces-config.xml which you can still use with Joinfaces.

**Comment by yashanet** [comment]
resolved
