### ISSUE TITLE
I am facing issues with <b:navLink

### ISSUE THREAD

**Issue by alanrene01** [joinfaces/joinfaces#887]
Hello, I am facing some issues because I am developing a new application using Bootsfaces, the issue is on Menu button, I am calling the proper method like this

```xml
<h:form>
      <b:navBar brand="Menu" brandHref="#" id="dropMenu" contentDisabled="false">
       <b:navbarLinks contentDisabled="false">
        <b:navLink value="Inicio" action="#"></b:navLink>
        <b:dropMenu value="Pipeline" contentDisabled="false">
           <b:navLink value="General" href="#{managerequest.pipeline()}"></b:navLink>
           <b:navLink value="Particular" action="#"></b:navLink>
        </b:dropMenu>
        <b:navLink value="Salir" action="#"></b:navLink>
       </b:navbarLinks>
     </b:navBar>
      </h:form>
```
    However, when I click on General option it gets come back to the login page, I am looking how to fix it but at this moment the issue persist.

**Comment by alanrene01** [comment]
Please @stephanrauh let me know your comments

**Comment by stephanrauh** [comment]
This is the bugtracker of JoinFaces, not BootsFaces :)

If I get you right, you're trying to use `<b:navLink>` to call Java methods. That's not possible - navLinks are simple links. However, you can use `<b:navCommandLink>`. It looks the same, but you can use it like a `<b:button>`.

Also see https://showcase.bootsfaces.net/layout/navLinks.jsf.

**Comment by melloware** [comment]
@alanrene01  please close this issue as its not JoinFaces related and should be opened on BootsFaces issues page.
